wireapp/wire-android-sync-engine

- tests/integration/src/test/scala/com/waz/conv/CreateConversationSpec.scala
- tests/mocked/src/test/scala/com/waz/mocked/MockedClientSuite.scala
- tests/mocked/src/test/scala/com/waz/mocked/MockedFlowManagerService.scala
- tests/unit/src/test/scala/com/waz/api/impl/RegistrationSpec.scala
- tests/unit/src/test/scala/com/waz/service/PushServiceSpec.scala
- tests/unit/src/test/scala/com/waz/service/avs/FlowManagerServiceSpec.scala
- tests/unit/src/test/scala/com/waz/service/call/VoiceChannelServiceSpec.scala
- tests/unit/src/test/scala/com/waz/service/push/LastNotificationIdServiceSpec.scala
- tests/unit/src/test/scala/com/waz/service/push/WebSocketClientServiceSpec.scala
- tests/unit/src/test/scala/com/waz/sync/ConversationsSyncHandlerSpec.scala
- tests/unit/src/test/scala/com/waz/sync/otr/OtrSyncHandlerSpec.scala
- tests/utils/src/main/scala/com/waz/testutils/MockModules.scala
- zmessaging/src/main/scala/com/waz/service/GlobalNotificationService.scala
- zmessaging/src/main/scala/com/waz/service/MetaDataService.scala
- zmessaging/src/main/scala/com/waz/service/UserService.scala
- zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
- zmessaging/src/main/scala/com/waz/service/call/FlowManagerService.scala
- zmessaging/src/main/scala/com/waz/service/conversation/ConversationEventsService.scala
- zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
- zmessaging/src/main/scala/com/waz/service/otr/OtrService.scala
- zmessaging/src/main/scala/com/waz/service/push/GcmGlobalService.scala
- zmessaging/src/main/scala/com/waz/service/push/GcmService.scala
- zmessaging/src/main/scala/com/waz/service/push/NotificationService.scala
- zmessaging/src/main/scala/com/waz/service/push/PushService.scala
- zmessaging/src/main/scala/com/waz/service/push/WebSocketClientService.scala
- zmessaging/src/main/scala/com/waz/sync/client/EventsClient.scala
- zmessaging/src/main/scala/com/waz/zms/GcmHandlerService.scala
- zmessaging/src/main/scala/com/waz/zms/PushService.scala
- zmessaging/src/main/scala/com/waz/znet/WebSocketClient.scala
Added `GcmService.gcmState` which determines if GCM is working (we are receiving notifications through it).
Changed WebSocket handling to enable always on socket connection always when GCM is not active, not only when play services are not available. 
This way we should get notification for new messages even if GCM is unreliable/broken.
> Gcm failure fallback

- zmessaging/src/main/scala/com/waz/service/push/GcmService.scala
- zmessaging/src/main/scala/com/waz/service/push/PushService.scala
GCM notification ids are kept in a set instead of just having a boolean
flag to better keep track of the notifications that got processed and
not. It also prevents getting stuck in a processing state in case of
processing failure.
Ticket: https://wearezeta.atlassian.net/browse/AN-4298
> [AN-4298] GCM notifications handling fix

- tests/unit/src/test/scala/com/waz/model/SyncJobDaoSpec.scala
- tests/utils/src/main/scala/com/waz/testutils/EmptySyncService.scala
- zmessaging/src/main/java/com/waz/model/sync/ReceiptType.java
- zmessaging/src/main/scala/com/waz/model/sync/SyncRequest.scala
- zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
- zmessaging/src/main/scala/com/waz/service/messages/EphemeralMessagesService.scala
- zmessaging/src/main/scala/com/waz/service/messages/MessagesService.scala
- zmessaging/src/main/scala/com/waz/service/messages/ReceiptService.scala
- zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
- zmessaging/src/main/scala/com/waz/sync/handler/MessagesSyncHandler.scala
This is not yet tested, feel free to try it out.
This is very basic implementation and has several limitations:
- obfuscated messages on sender will be removed when any recipient confirms deletion
- in case new user was just added to conv to which we are sending ephemeral message it may happen that new user will not receive the message, we would need to add handling on BE to support that properly
> Add handling for ephemeral messages in group conversations.

- actors/remote_app/src/it/scala/com/waz/RemoteActorAppSpec.scala
- env-credentials.sbt
- project/SharedSettings.scala
- zmessaging/src/main/scala/com/waz/service/push/WebSocketClientService.scala
Fix 1:  Remove Edge backend from SharedSettings and RemoteActor.
**Please be careful:**
When merge it, you also need to update credentials.sbt in Jenkins, otherwise it will raise exception immediately.
Fix 2: (From @deanrobertcook )
Fix the WebSocket cannot be disconnected when Account logout.
> Remove Edge from Remote Actor and SharedSettings.InternalBackendPasswords

- zmessaging/src/main/scala/com/waz/service/messages/EphemeralMessagesService.scala
Timer should be started Not only for Asset, but also for ImageAsset.
(PS: the modification is on SE itself, not in Actor)
> Bug fix: Cannot start timer for ephemeral image

- build.sbt
- project/SharedSettings.scala
We need this version to run actors app together with a cryptobox we compiled for windows. This makes it possible for us to run tests for Windows Wrapper that uses the actors app.
> Update to newer version of cryptobox for actors app

- tests/unit/src/test/scala/com/waz/api/impl/UsernamesSpec.scala
- tests/utils/src/main/scala/com/waz/testutils/EmptySyncService.scala
- zmessaging/src/main/java/com/waz/api/ValidatedUsernames.scala
- zmessaging/src/main/java/com/waz/model/sync/SyncCommand.java
- zmessaging/src/main/scala/com/waz/api/impl/User.scala
- zmessaging/src/main/scala/com/waz/api/impl/Usernames.scala
- zmessaging/src/main/scala/com/waz/api/impl/ValidatedHandles.scala
- zmessaging/src/main/scala/com/waz/api/impl/ZMessagingApi.scala
- zmessaging/src/main/scala/com/waz/model/sync/SyncRequest.scala
- zmessaging/src/main/scala/com/waz/service/AccountService.scala
- zmessaging/src/main/scala/com/waz/service/HandlesService.scala
- zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
- zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
- zmessaging/src/main/scala/com/waz/sync/client/HandlesClient.scala
- zmessaging/src/main/scala/com/waz/sync/handler/HandlesSyncHandler.scala
- zmessaging/src/main/scala/com/waz/utils/JsonDecoder.scala
Uses sync handler instead of a direct request to avoid letting the UI handle with failed requests.
> Add sync request to check for availability of usernames

- zmessaging/src/main/scala/com/waz/service/UserService.scala
There was a bug on production that erased users pictures in the database. While the bug has been fixed already, affected users won’t receive the picture unless the other users change it. This fix forces a syncUser if there is no picture info in the database.
> Workaround for erased users pictures

- zmessaging/src/main/scala/com/waz/model/AssetData.scala
- zmessaging/src/main/scala/com/waz/model/AssetMetaData.scala
- zmessaging/src/main/scala/com/waz/ui/Images.scala
Local assets created from URI were getting created with no dimension data.
Ticket: https://wearezeta.atlassian.net/browse/AN-4782
> [AN-4782] Issue with local assets

- zmessaging/src/main/scala/com/waz/content/MessagesCursor.scala
- zmessaging/src/main/scala/com/waz/utils/events/Signal.scala
Changed `WindowLoader` to take a range od indices as a paramter,
previously it only used single index and would return currently loaded window if it contained given index.
As a result `getEntries` would receive a window which doesn't contain all requested entries and lead to errors in UI.
Also included small improvement for `Signal.currentValue` to prevent showing autowiring warning when not necessary.
>  Fix `MessagesCursor.getEntries`.

- zmessaging/src/main/scala/com/waz/model/AssetData.scala
- zmessaging/src/main/scala/com/waz/sync/handler/AssetSyncHandler.scala
We still want to be able to use asset uris as cache keys to prevent duplicate entries of the same asset in cache storage, however some URIs do not provide a unique point of access, and for these we should then default to using the asset id as the cache key.
> Add a blacklist of URIs to use as Asset cache keys

- zmessaging/src/main/scala/com/waz/model/NotificationData.scala
- zmessaging/src/main/scala/com/waz/model/Uid.scala
Decoder was not loading id correctly, `NotId` had constructor taking symbol, so implicit for string decoding would not be used, instead all notifications would have `'id` for id value. Due to this notifications map signal in storage would not return all notifications.
This caused several weird issues with notifications list, like missing notifications or randomly showing old ones.
> [AN-5019] Fix NotificationData decoding.

- zmessaging/src/main/scala/com/waz/api/impl/ImageAsset.scala
Since the data might not have been initialised by the time
saveImageToGallery is called, it’s safer to get it from the storage
when saving.
> [AN-5034] Save image to gallery from ImageAsset doesn't rely on data

- zmessaging/src/main/scala/com/waz/content/KeyValueStorage.scala
- zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
- zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
- zmessaging/src/main/scala/com/waz/sync/client/ConversationsClient.scala
The backend is still sending past participants and we were ignoring the
status. It also forces conversation sync after migration to restore the
damaged ones.
> Fix issue with past participants

- project/SharedSettings.scala
- tests/integration/src/test/scala/com/waz/messages/AssetMessageSpec.scala
- tests/unit/src/test/scala/com/waz/Generators.scala
- tests/unit/src/test/scala/com/waz/service/images/ImageLoaderSpec.scala
- zmessaging/src/main/res/values/zms_preferences.xml
- zmessaging/src/main/scala/com/waz/model/AssetData.scala
- zmessaging/src/main/scala/com/waz/model/GenericContent.scala
- zmessaging/src/main/scala/com/waz/service/PreferenceService.scala
- zmessaging/src/main/scala/com/waz/service/messages/MessagesService.scala
- zmessaging/src/main/scala/com/waz/sync/handler/MessagesSyncHandler.scala
Uses generic-message-proto 1.19.0 which adds an optional enum, EncryptionAlgorithm, which can be either AES_CBC (the old one), or AES_GCM (the new one). 
The new algorithm is not implemented yet, so instead there is a new switch in PreferenceService, v31AssetsEnabled, by default set to false. Only if the switch was set to true and the AES_GCM was set in AssetData, the new algorithm would be used to decrypt received data.
Accidentally, the new generic-message-proto also incorporates one small change in Messages.Confirmation: messageId is changed to firstMessageId.
> [AN-5151] adds asset v3.1 receiving possibility

- external/build.sbt
- project/SharedSettings.scala
The replacement artifact is newer than the current artifact despite the version number.
The new dependency is Apache 2.0 licensed, whereas the old one is proprietary.
Also remove the library from external build script.
> Update spotify-auth dependency to publicly available maven artifact

- zmessaging/src/main/scala/com/waz/service/PreferenceService.scala
`gcmEnabledKey` is for Google Cloud Messaging, not Galois/Counter Mode ;)
> Wrong GCM here pref used

- zmessaging/src/main/java/com/waz/api/NetworkMode.java
- zmessaging/src/main/scala/com/waz/api/impl/ConnectionIndicator.scala
- zmessaging/src/main/scala/com/waz/service/NetworkModeService.scala
- zmessaging/src/main/scala/com/waz/service/messages/DefaultMessagesService.scala
- zmessaging/src/main/scala/com/waz/sync/handler/MessagesSyncHandler.scala
- zmessaging/src/main/scala/com/waz/sync/queue/SyncExecutor.scala
No longer assume offline on startup, but set mode to Unknown. This will help UI to not briefly display the offline indicator at app startup.
> Introduced new Unknown network mode

- zmessaging/src/main/scala/com/waz/utils/CachedStorage.scala
Until recently comparing two AssetData always returned false which forced unnecessary updates in CachedStorage. I changed that but it uncovered another error: When two AssetData were the same, the update method returned None, whereas everyone expected to have a tuple: the old and the new AssetData (even if they were the same). This PR fixes that.
> makes CachedStorage return an asset instead of None if the update was not necessary

- tests/integration/src/test/scala/com/waz/sync/client/AssetClientSpec.scala
- tests/unit/src/test/scala/com/waz/service/images/BitmapSignalSpec.scala
- tests/unit/src/test/scala/com/waz/service/images/ImageLoaderSpec.scala
- zmessaging/src/main/scala/com/waz/api/impl/ImageAsset.scala
- zmessaging/src/main/scala/com/waz/service/images/BitmapSignal.scala
Removed code for old handling of preview images, we no londer report previews.
Added check for requested image size and preview availability.
When requested image is small and preview is big enough we want to only load preview image instead of full one.
This is especially usefull for chathead images, where smallProfile version is big enough in most cases.
Loading smaller previews is much faster and uses less memory, full images were exhausting memory image cache (causing even worse performance).
> Fix BitmapSignal to use preview image when possible.

- tests/integration/src/test/scala/com/waz/messages/AssetMessageSpec.scala
- tests/integration/src/test/scala/com/waz/messages/ImageAssetMessageSpec.scala
- tests/integration/src/test/scala/com/waz/messages/LastReadSpec.scala
- tests/integration/src/test/scala/com/waz/messages/VideoMessageSpec.scala
- tests/integration/src/test/scala/com/waz/service/otr/OtrIntegrationSpec.scala
- tests/mocked/src/test/scala/com/waz/mocked/MockedClientSuite.scala
- tests/unit/src/test/scala/com/waz/cache/CacheServiceSpec.scala
- tests/unit/src/test/scala/com/waz/service/AssetServiceSpec.scala
- tests/unit/src/test/scala/com/waz/service/assets/DownloaderServiceSpec.scala
- tests/unit/src/test/scala/com/waz/service/images/ImageLoaderAndroidFreeSpec.scala
- tests/unit/src/test/scala/com/waz/sync/PostMessageHandlerSpec.scala
- tests/unit/src/test/scala/com/waz/sync/handler/AssetSyncHandlerSpec.scala
- tests/unit/src/test/scala/com/waz/sync/handler/ImageAssetSyncHandlerSpec.scala
- zmessaging/src/main/scala/com/waz/cache/CacheService.scala
- zmessaging/src/main/scala/com/waz/cache/LocalData.scala
- zmessaging/src/main/scala/com/waz/service/GlobalModule.scala
- zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
- zmessaging/src/main/scala/com/waz/service/assets/AssetLoader.scala
- zmessaging/src/main/scala/com/waz/service/assets/AssetService.scala
- zmessaging/src/main/scala/com/waz/service/messages/DefaultMessagesService.scala
- zmessaging/src/main/scala/com/waz/sync/client/AssetClient.scala
- zmessaging/src/main/scala/com/waz/sync/handler/AssetSyncHandler.scala
- zmessaging/src/main/scala/com/waz/sync/handler/MessagesSyncHandler.scala
- zmessaging/src/main/scala/com/waz/sync/handler/UsersSyncHandler.scala
- zmessaging/src/main/scala/com/waz/sync/otr/OtrSyncHandler.scala
- zmessaging/src/main/scala/com/waz/znet/ZNetClient.scala
The current version of AN-5163 fix prevents the receiver from displaying a dark container and the sender from displaying an invalid "Delivered" footer. However, the sender has to tap "Retry" in order to retry sending. It would be nice to have automatic retries.
> AN-5163 bugfix. Android-free unit tests in AssetSyncHandler. 

- tests/unit/src/test/scala/com/waz/znet/AsyncClientSpec.scala
- zmessaging/src/main/scala/com/waz/service/downloads/Downloader.scala
- zmessaging/src/main/scala/com/waz/service/downloads/DownloaderService.scala
- zmessaging/src/main/scala/com/waz/znet/AsyncClient.scala
Asset download is retried with the max time set to one week, which in practice means that eventually the user will just leave the conversation and when she comes back, the downloading will be tried again. Simplifies DownloaderService.
Removes one 'cancel' call from AsyncClient which was dead code.
> fixes AN-5223 and AN-5190: asset download is retried practically forever 

- zmessaging/src/main/scala/com/waz/znet/AsyncClient.scala
The internal AsyncHttpClient's timeout may interfere in situations when the download is slow, but steady. In such situations our "smart" timeout, on the AsyncClient level, is not triggered, but the AsyncHttpClient's one may still be. 
And it's not needed anyway.
> removes the AsyncHttpClient's timeout; we use our own

- zmessaging/src/main/scala/com/waz/service/assets/AssetService.scala
- zmessaging/src/main/scala/com/waz/service/messages/EphemeralMessagesService.scala
- zmessaging/src/main/scala/com/waz/ui/MemoryImageCache.scala
Fix to AN-5266 was to delete ephemeral videos and audios form the temporary folder, but it also deleted images. If the user sent an ephemeral photo, she was not able to see it anymore in the Wire's gallery. Fixed that.
> [AN-5266] ephemeral images are being deleted from the storage

- zmessaging/src/main/scala/com/waz/content/Preferences.scala
It will still require the UI to start using this instead
> Add preference for dark theme

- tests/unit/src/test/scala/com/waz/znet/AsyncClientSpec.scala
- zmessaging/src/main/scala/com/waz/znet/AsyncClient.scala
- zmessaging/src/main/scala/com/waz/znet/HttpRequest.scala
Everything works the same as before, but RequestWorker.processRequest exists only because we need a way t go around AsyncHttpRequest limitations. As such, it's better to keep it as simple as possible and, for example, prepare the headers before it is called.
> user_agent set in headers in AsyncClient instead of RequestWorker

- tests/unit/src/test/scala/com/waz/service/AccountsServiceSpec.scala
- zmessaging/src/main/scala/com/waz/model/AccountData.scala
- zmessaging/src/main/scala/com/waz/service/AccountManager.scala
- zmessaging/src/main/scala/com/waz/sync/otr/OtrClientsSyncHandler.scala
Ensures that each step of the ensureFullyRegistered method is responsible for updating the account storage completely before passing onto the next step - there was a bug where one step expected it to be done, but the account was only updated in memory, leading to client registration state loss and ultimately registered multiple clients per login.
This commit also tidies up the method, making it flatter - the error is only used in one spot to determine if we should create a zms instance or not.
> Update account data correctly in registration

- zmessaging/src/main/scala/com/waz/service/AccountsService.scala
I was not able to reproduce the bug. Please test it with this one-liner.
> [AN-5475] Logged-in accounts should also filter for accounts with a defined clientId

- zmessaging/src/main/scala/com/waz/service/otr/OtrServiceImpl.scala
Decided to make a separate entry instead of relying on the catch all, since I'm not sure how often this happens and don't want to spam the user's conversations
> Split duplicate/outdated otr error and save exception

- actors/base/src/main/scala/com/waz/provision/DeviceActor.scala
- tests/mocked/src/test/scala/com/waz/mocked/connections/InitialConnectionStatusSpec.scala
- tests/unit/src/test/scala/com/waz/service/UserSearchServiceSpec.scala
- tests/unit/src/test/scala/com/waz/service/teams/TeamConversationSpec.scala
- tests/utils/src/main/scala/com/waz/testutils/EmptySyncService.scala
- zmessaging/src/main/java/com/waz/model/sync/SyncCommand.java
- zmessaging/src/main/scala/com/waz/api/impl/ConnectionsSearch.scala
- zmessaging/src/main/scala/com/waz/api/impl/ZMessagingApi.scala
- zmessaging/src/main/scala/com/waz/api/impl/search/ConversationSearchResult.scala
- zmessaging/src/main/scala/com/waz/api/impl/search/Search.scala
- zmessaging/src/main/scala/com/waz/api/impl/search/UserSearchResult.scala
- zmessaging/src/main/scala/com/waz/content/MessagesStorage.scala
- zmessaging/src/main/scala/com/waz/content/SearchQueryCacheStorage.scala
- zmessaging/src/main/scala/com/waz/content/UsersStorage.scala
- zmessaging/src/main/scala/com/waz/model/Handle.scala
- zmessaging/src/main/scala/com/waz/model/sync/SyncRequest.scala
- zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
- zmessaging/src/main/scala/com/waz/service/UserService.scala
- zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
- zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
- zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
- zmessaging/src/main/scala/com/waz/sync/client/HandlesClient.scala
- zmessaging/src/main/scala/com/waz/sync/client/UserSearchClient.scala
- zmessaging/src/main/scala/com/waz/sync/handler/HandlesSyncHandler.scala
- zmessaging/src/main/scala/com/waz/sync/handler/UserSearchSyncHandler.scala
- zmessaging/src/main/scala/com/waz/utils/Locales.scala
* Lots of user searching functionality moved from UI to SE
* If `UserData` with the exact handle match is not found with the standard search, a new request is used to search for that on the backend
* Refactoring to allow android-free unit tests of `UserSearchService` and unit tests covering the standard search
* A hack: garbage collection is enforced before the search to lower the risk of GC suspending the search in-between
* Still to do: more unit tests!
> [AN-5406] Searches for the exact handle match

- .travis.yml
- tests/integration/src/test/scala/com/waz/conv/ConversationsSpec.scala
- tests/integration/src/test/scala/com/waz/conv/CreateConversationSpec.scala
- tests/integration/src/test/scala/com/waz/conv/LargeConversationsListSpec.scala
- zmessaging/src/main/scala/com/waz/api/ConversationsList.scala
- zmessaging/src/main/scala/com/waz/api/impl/ConversationsList.scala
A small change connected to rewriting ScalaConversationStore from Java to Scala. The rest of the code changes are in UI.
> ConversationsList.createGroupConversation uses Seq instead of Java Iterable

- tests/unit/src/test/scala/com/waz/service/assets/AssetLoaderServiceSpec.scala
- zmessaging/src/main/scala/com/waz/service/downloads/AssetLoaderService.scala
The bugs are difficult to reproduce. I suspect they are all related to that the Scala's mutable PriorityQueue is not thread-safe and when many threads try to modify it concurrently this may cause weird behaviour. 
Especially the `IndexOutOfBoundsException` from AN-5534 hints to that, as explained here in the first comment: https://stackoverflow.com/questions/31847852/is-scalas-collection-mutable-priorityqueue-thread-safe
I've rewritten the code so that all operations modifying the queue are now in a synchronized block.
> [AN-5534] [AN-5541] [AN-5542] makes loading entries priority queue thread-safe

- zmessaging/src/main/scala/com/waz/service/messages/MessageEventProcessor.scala
A small refactoring I did while working on AssetLoaderService.
MessageEventProcessor correctly handles link previews with multiple images.
> saves multiple assets from link previews

- tests/unit/src/test/scala/com/waz/api/impl/UsernamesSpec.scala
- zmessaging/src/main/scala/com/waz/api/impl/ConnectionsSearch.scala
- zmessaging/src/main/scala/com/waz/model/Handle.scala
- zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
- zmessaging/src/main/scala/com/waz/sync/handler/UserSearchSyncHandler.scala
- zmessaging/src/main/scala/com/waz/utils/Locales.scala
Also, transliteration may remove the underscore signs from handles, so I introduced an "or" in matching the query with the handle. Either the transliterated or the raw version should match.
And the standard (ie. not exact) handle match is now "startsWith", not "contains". In case of handles, since the query has to start with '@', we don't look for handles which have the query somewhere inside, but only at the beginning.
> [AN-5406] user search waits for UserData for the exact match before asking for it

- tests/unit/src/test/scala/com/waz/api/impl/UsernamesSpec.scala
- tests/unit/src/test/scala/com/waz/service/UserSearchServiceSpec.scala
- zmessaging/src/main/scala/com/waz/api/impl/search/UserSearchResult.scala
- zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
Recently `UserSearchService` was changed to the point where a part of old code became redundant. This PR simplifies the `searchUserData` method. There are two changes to its functionality:
1. Before we created a new signal for each new query, now we reuse them if the query was not forgotten yet. 
2. One small corner case bug is fixed: If the user typed in a query starting with an '@' sign (which triggers an exact match search), changed the query before the exact match search completed, and then typed it again, the exact match search might never be repeated.
> rewrites searchUserData in UserSearchService

- tests/unit/src/test/scala/com/waz/Generators.scala
- tests/utils/src/main/scala/com/waz/api/ApiSpec.scala
- zmessaging/src/main/scala/com/waz/api/impl/conversation/BaseConversation.scala
- zmessaging/src/main/scala/com/waz/content/MessagesStorage.scala
- zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
- zmessaging/src/main/scala/com/waz/model/ConversationData.scala
- zmessaging/src/main/scala/com/waz/service/conversation/ConversationsListStateService.scala
Changed `ConversationData.unreadCount` to report separate counts for messages, calls and pings. This info can be used to display conversations list more efficiently.
We should also add unread `likes` counter in similar way, but we need to better define what 'unread' actually means for likes (there can be new likes for pretty old messages).
> Add more granular unread messages counting.

- build.sbt
- zmessaging/src/main/scala/com/waz/znet/ClientWrapper.scala
It seems as though the Android Async library has been updated to handle the SNI problem we had to hack recently. 
For convenience here is a comparison of the changes to the library since the last version we imported: https://github.com/koush/AndroidAsync/compare/54c55a47e14653e62ddfe96489d25b28cb079268...master#diff-1854451d46929eb681631dc3ebfec0d6L9
Would like to test this a lot more before merging.
> Update AndroidAsync library

- tests/unit/src/test/scala/com/waz/service/push/PushTokenServiceSpec.scala
- zmessaging/src/main/scala/com/waz/content/Preferences.scala
- zmessaging/src/main/scala/com/waz/service/BackendConfig.scala
- zmessaging/src/main/scala/com/waz/service/GlobalModule.scala
- zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
- zmessaging/src/main/scala/com/waz/service/call/FlowManagerService.scala
- zmessaging/src/main/scala/com/waz/service/push/PushTokenService.scala
- zmessaging/src/main/scala/com/waz/utils/wrappers/GoogleApi.scala
- zmessaging/src/main/scala/com/waz/zms/FCMHandlerService.scala
- zmessaging/src/main/scala/com/waz/zms/InstanceIdListenerService.scala
Should ensure that `getToken` and `deleteInstanceId` are continually retried until successful in case of IOExceptions from `FCMInstanceId`
> Retry getToken and deleteInstanceId until successful

- zmessaging/src/main/scala/com/waz/content/MessagesStorage.scala
This is a quick fix for the unread dot: If an availability status is received by an old client, it is counted as a message of the type UNKNOWN. It does not appear anywhere, but is still counted as unread.
Here I just added one more check to counting unread messages - if the message is of the type UNKNOWN, it's not counted. (Status changes are already filtered out in the new clients, so they are not counted at all). We should also implement to clear all UNKNOWN messages already in the database.
APK for testing: https://drive.google.com/open?id=1rNBHVZ7Kn7BtWfmOSGc4-o-gVz3CkpQO
> [AN-5845] fix for availability messages being counted as unread

- tests/unit/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
- zmessaging/src/main/scala/com/waz/service/call/CallingService.scala
Use case: When calling a bot in a 1-to-1 conversation the calling screen displays "group conversation". It should display the name of the bot.
> use ConversationsService to check if the call is a group one

- zmessaging/src/main/jni/Android.mk
- zmessaging/src/main/jni/LzwDecoder.cpp
- zmessaging/src/main/jni/LzwDecoder.h
- zmessaging/src/main/scala/com/waz/bitmap/gif/LzwDecoder.scala
This PR adds some missing bounds checking as pointed out in the security review.
Another approach to this would be changing the types from signed to unsigned, but this seemed simpler. @marcoconti83 can you take a look at this? My C++ is pretty rusty.
For the 3rd and final issue stated in the report, the review states that values other than 31 could cause overflow, but I couldn't replicate this in testing, so I think this is erroneous. `clear = 0` should never cause the check to pass. However, overflow/underflow is one of those super tricky things so I'd appreciate some other eyes on this.
> [AN-5752] Fix bounds checking in LzwDecoder

- zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
- Let SQLite allocate event indexes automatically, to avoid crashes
during migration.
> Fix migration crash

- zmessaging/src/main/scala/com/waz/model/sync/SyncRequest.scala
- zmessaging/src/main/scala/com/waz/sync/client/UsersClient.scala
- zmessaging/src/main/scala/com/waz/sync/handler/ConversationsSyncHandler.scala
- zmessaging/src/main/scala/com/waz/znet/AsyncClient.scala
- zmessaging/src/main/scala/com/waz/znet/HttpResponse.scala
The most important change here is simply increasing the limit for user ids sent in the "create conversation" request. It's now set to 256 which means that we practically won't use the "add members to the conversation" request at this point, as 256 is the conversation size limit anyway. 
Also, in merging sync jobs, I changed the `forall` check to `subsetOf` - it does the same but is optimized for hash sets, so we can expect a bit better performance.
The limit for the number of user ids in one sync request was increased from 45 to 64. It doesn't do much, but again, it might improve performance a little (fewer requests). Increasing this limit more than that results in a failure response (uri too large). 
~~I created methods `syncUsers` in `UserService`, and `take(number: Int)` in …
> Improve performance of creating large conversations and syncing users

- zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
When creating a conv with a bot, the app first creates a conv with only the user and then adds the bot to it. But until now the check if the conv is a group one was at one point checking if the number of users in the conv is exactly 2. 
I also noticed that in most cases the original `isGroupConversation` method, which returns a future, is immediately wrapped in a signal. So, I created a `groupConversation` method, which returns a signal and can be used without that intermediate step. 
Actually, this bug shows that the one-to-one/group status of the conversation might change during initialization and only then is stable, so using a signal instead of a future might be safer.
> Fix a 1:1 conv with bot allowing adding other participants

- tests/unit/src/test/scala/com/waz/permissions/PermissionsServiceSpec.scala
- zmessaging/src/main/scala/com/waz/permissions/PermissionsService.scala
- zmessaging/src/main/scala/com/waz/service/ContactsService.scala
- zmessaging/src/main/scala/com/waz/service/assets/AssetService.scala
- zmessaging/src/main/scala/com/waz/service/call/CallingService.scala
- zmessaging/src/main/scala/com/waz/service/images/ImageLoader.scala
This should guarantee the order in which permissions are requested
> Use ListSet in permissions service

- zmessaging/src/main/scala/com/waz/model/AssetData.scala
- zmessaging/src/main/scala/com/waz/model/Mime.scala
- zmessaging/src/main/scala/com/waz/service/assets/AssetService.scala
Sent audio assets can't be played directly on iOS, because they don't have file extensions:
https://github.com/wireapp/android-project/issues/229
I decided to generalize it a bit and add file extensions to all supported file types.
> Add file extensions to asset names

- tests/unit/src/test/scala/com/waz/service/connections/ConnectionServiceSpec.scala
- zmessaging/src/main/scala/com/waz/content/ConversationStorage.scala
- zmessaging/src/main/scala/com/waz/service/ConnectionService.scala
- zmessaging/src/main/scala/com/waz/service/conversation/ConversationsContentUpdater.scala
When the user puts a device in the airplane mode or switched it off, and then created a new conversation (or just a connection request) using another device, and then switched on the first device, the syncing resulted in duplicated entries in the conversations table.
Note: This commit fixes the bug, but does not correct the already duplicated entries. For that a method introduced in another commit (63bdf03), `ConversationsContentUpdater.fixDuplicatedConversations`, has to be used.
fixes: https://github.com/wireapp/android-project/issues/260
> fix: corrects the way we update remoteMap in ConversationStorage

- project/SharedSettings.scala
- tests/unit/src/test/scala/com/waz/Generators.scala
- tests/unit/src/test/scala/com/waz/model/MessageDataDaoSpec.scala
- tests/unit/src/test/scala/com/waz/model/MessageDataSpec.scala
- tests/unit/src/test/scala/com/waz/service/MessageEventProcessorSpec.scala
- tests/unit/src/test/scala/com/waz/service/UserSearchServiceSpec.scala
- tests/unit/src/test/scala/com/waz/service/conversation/MessageSendingSpec.scala
- tests/unit/src/test/scala/com/waz/service/media/RichMediaContentParserSpec.scala
- tests/unit/src/test/scala/com/waz/service/otr/OtrSyncHandlerSpec.scala
- zmessaging/src/main/scala/com/waz/content/MessagesStorage.scala
- zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
- zmessaging/src/main/scala/com/waz/model/ConversationData.scala
- zmessaging/src/main/scala/com/waz/model/GenericContent.scala
- zmessaging/src/main/scala/com/waz/model/Mention.scala
- zmessaging/src/main/scala/com/waz/model/MessageData.scala
- zmessaging/src/main/scala/com/waz/model/package.scala
- zmessaging/src/main/scala/com/waz/service/SearchKey.scala
- zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
- zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
- zmessaging/src/main/scala/com/waz/service/media/RichMediaContentParser.scala
- zmessaging/src/main/scala/com/waz/service/messages/MessageEventProcessor.scala
- zmessaging/src/main/scala/com/waz/service/messages/MessagesService.scala
- zmessaging/src/main/scala/com/waz/service/otr/OtrServiceImpl.scala
- zmessaging/src/main/scala/com/waz/service/push/NotificationService.scala
- zmessaging/src/main/scala/com/waz/sync/handler/MessagesSyncHandler.scala
We already had `mentions` in the protobuf and handled it in `MessageContent`, but they were not used in the app. Now we want to introduce them properly, and that means changes both to how they are encoded in the protobuf, and new code which actually uses them.
New `Mention`s can be now sent from `ConversationsUiService.addTextMessage`.
They are added to `MessageContent`s of `MessageData` and adjusted for the specified charset.
We differentiate between two charsets: UTF-16 and default. When we want to send a message,
we specify that the mentions in that message should be adjusted for UTF-16. When we receive
one, we need to re-adjust the mentions for our default charset (UTF-8 on Android). Sending
and receiving messages use common fuctionality in MessageData: `messageContent`. Before this …
> feat: new Mentions

- zmessaging/src/main/scala/com/waz/model/Mime.scala
- zmessaging/src/main/scala/com/waz/service/assets/AssetService.scala
- zmessaging/src/main/scala/com/waz/service/downloads/AssetLoader.scala
- zmessaging/src/main/scala/com/waz/service/downloads/AssetLoaderService.scala
I assume the filename has file extension simply if it contains a '.' sign. Also, I added a ".txt" file extension to the Mime map.
fixes https://github.com/wireapp/android-project/issues/259
> fix: Don't add file extensions to filenames with file extensions

- zmessaging/src/main/scala/com/waz/content/ConversationStorage.scala
- zmessaging/src/main/scala/com/waz/content/Preferences.scala
- zmessaging/src/main/scala/com/waz/service/conversation/ConversationsContentUpdater.scala
A bug introduced in a previous release broke the way new conversations were created. Instead of adding one entry to the conversations table and then updating it, the bug was creating a new entry, with a new local id, and the same remote id. The app wasn't then able to display the new conversation on the conversations list, and display messages in this conversation.
The bug was fixed, but the duplicate entries already created were left in the database. This commit removes them and corrects the original one. It should run only once, just after the update to the release with the fix.
We can suspect that in at most a few months all clients with the duplicated entries in the database will be fixed and we will be able to remove the code.
for more info about this please look at …
> fix: removes duplicated entries in the conversations table

- zmessaging/src/main/scala/com/waz/model/sync/SyncRequest.scala
- zmessaging/src/main/scala/com/waz/service/push/PushTokenService.scala
- zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
- zmessaging/src/main/scala/com/waz/sync/client/PushTokenClient.scala
- zmessaging/src/test/scala/com/waz/service/push/PushTokenServiceSpec.scala
- zmessaging/src/test/scala/com/waz/sync/client/PushTokenClientSpec.scala
Due to a race where we might accidentally unregister our own push
token from the BE without noticing, it can be that some users in the
wild have no push token.
This commit implements functionality to fetch all registered push tokens
on the BE for a given user, upon which the PushTokenService will compare
these tokens with the one it thinks is registered. If there is no match,
then it will re-register the current device token with the backend.
This commit only provides the above described functionality, but does
not schedule the check. This will be determined in the Android (UI)
project - the best time to do it would be on app start and app upgrade.
partly fixes: https://github.com/wireapp/android-project/issues/263
> fix: check for potentially out of sync push token

- zmessaging/src/main/scala/com/waz/service/call/CallInfo.scala
- zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
- zmessaging/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
Also shouldn't replace an existing call with the same id.
> fix: onIncomingCall should respect the shouldRing flag

- zmessaging/src/main/scala/com/waz/service/call/CallInfo.scala
- zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
- zmessaging/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
onIncomingCall should update the call profile unless it's for a group check, which occurs on an ongoing call. Terminating or Ended calls should be discarded.
> fix: onIncomingCall should replace finished calls from the profile

- zmessaging/src/main/scala/com/waz/service/images/ImageLoader.scala
In upgrading to android 8, we moved all file uris (`file:///`) to
content uris (`content:///`) to be complient with changes introduced in
android 7, however these uris don't seem to work with the media scanner
and so our saved images stopped appearing in the system as images.
This creates 2 uris, one file type, to be used by the scanner, and
another content type, to be returned to other parts of the app that will
then share this URI with other applications via other types of intents.
Testing
- Save an image on Android version >= 7, open the image from the
generated notification and make sure it doesn't crash
- Save an image on any android version, and make sure that image
appears in the gallery (or any other application)
> fix: use fileUri for broadcast to media scanner

- zmessaging/src/main/scala/com/waz/content/UsersStorage.scala
- zmessaging/src/main/scala/com/waz/model/UserData.scala
- zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
- zmessaging/src/main/scala/com/waz/service/conversation/NameUpdater.scala
- zmessaging/src/main/scala/com/waz/service/teams/TeamsService.scala
Until now when a user was removed from our team, we removed that user's data completely from the database. That was inconsistent with what happened when the user actually deleted their account: in that case we just marked the user as deleted, but we were still able to retrieve the data if needed.
This fix makes users removed from the team also just marked as deleted.
The most important purpose of that is for the other users to be able to read old conversations. Even if some of the participants are not longer in the team, we should be able to display information about them in these conversations.
It also means that if a user is removed from a team, and then restored, we don't lose the history of the one-to-one conversation with them.
> fix: Users removed from the team are marked as deleted instead of being deleted

- zmessaging/src/main/scala/com/waz/service/conversation/ConversationOrderEventsService.scala
- zmessaging/src/test/scala/com/waz/service/conversation/ConversationOrderEventsServiceSpec.scala
Fixes a bug that unarchived conversation with every reply, no matter to what user in the conversation it was a reply to.
I used this opportunity to refactor the method which checks if the conversation should be unarchived, and to write a couple of unit tests.
> fix: Unarchive conversations with a reply only if it's quoting the current user

- zmessaging/src/main/scala/com/waz/service/messages/MessageEventProcessor.scala
- zmessaging/src/main/scala/com/waz/utils/crypto/ReplyHashing.scala
- zmessaging/src/test/scala/com/waz/service/MessageEventProcessorSpec.scala
- zmessaging/src/test/scala/com/waz/utils/crypto/ReplyHashingSpec.scala
Right now when processing new events, and it turns out they are messages with quotes, the validity of each quote is checked one by one. It means that for each quote the storage is accessed separately for the `MessageData`. This PR changes that: all original messages are retrieved in one call.
> feat: Batch quote checking in MessageEventProcessor

- zmessaging/src/main/scala/com/waz/content/MessagesStorage.scala
The SQL query isn't enough to filter out the messages in between the provided timestamps
> fix: Use correct predicate for the findMessagesBetween

- zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
- zmessaging/src/main/scala/com/waz/service/otr/OtrClientsService.scala
- zmessaging/src/main/scala/com/waz/sync/handler/MessagesSyncHandler.scala
- zmessaging/src/main/scala/com/waz/sync/otr/OtrSyncHandler.scala
- zmessaging/src/test/scala/com/waz/sync/handler/MessagesSyncHandlerSpec.scala
When sending a message offline, it should fail and ask the user to resend.
> fix: Message sending should fail when on offline instead of retrying

- zmessaging/src/main/scala/com/waz/service/BackendConfig.scala
- zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
- zmessaging/src/main/scala/com/waz/service/push/WSPushService.scala
- BackendConfig can be moved to UI, as it isn't required in SE
and it's now being injected from UI anyway
> Remove BackendConfig, move it to UI

- zmessaging/src/main/scala/com/waz/sync/SyncRequestService.scala
- zmessaging/src/main/scala/com/waz/sync/handler/TypingSyncHandler.scala
Recent introduction of `RequestInfo` broke the typing indicator.
In `TypingSyncHandler` we check if the request is not too much delayed, by checking the job's `startTime`. But due to other requirements, if there is no delay at all, we have the `startTime` set to 0, not to `now()`, which meant that the request was always delayed too much. I added a check for that.
> fix: Send a typing indicator event

- zmessaging/src/main/scala/com/waz/content/MessagesStorage.scala
- When opening a cleared conversation from the searchUI
messages from before the clearing would still show.
- This commit adds a missing notification of changes which resulted in the cached `MessagesListView` displaying deleted content
- Fixes wireapp/android-project#391
> fix: messages which were deleted still showing up

- zmessaging/src/test/scala/com/waz/model/MessageAndLikesStorageSpec.scala
During my investigation for https://github.com/wireapp/wire-android/pull/1988 I could not find any test about the sorting of likes so I created one
There are a few methods to get likes, I only tested `getMessageAndLikes` which is the one used on the UI.
> test: Add test for sorting of likes

- zmessaging/src/test/scala/com/waz/service/MessagesServiceSpec.scala
This PR contains two new tests for the `addRenameConversationMessage` in `MessagesServiceImpl`.  The tests handle two particular cases:
1. adding a rename conversation message for the first time,
2. updating an existing rename conversation message.
> Test messages service

- zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
- zmessaging/src/test/scala/com/waz/service/conversation/ConversationServiceSpec.scala
When the user leaves the conversation from another device, the current device should archive the conversation. This is not happening at the moment.
When the app receives a `conversation.member-leave` that removes the currently logged in user, and the user was the one that triggered the event, then the conversation is archived.
- Unit tests for a positive case (should archive) and a negative cases:
- should not archive because triggered by a different user
- should not archive because it's not the user that is being removed
- Manual test on device:
- Leave the conversation from another device: conversation archived ✅
- Have another user remove the user from another device: conversation not archived ✅
The constructor for `ConversationServiceSpec` has too many parameters and depends on so …
> Archive a conversation when the user leaves remotely

- zmessaging/src/main/scala/com/waz/model/UserData.scala
- zmessaging/src/test/scala/com/waz/model/UserDataSpec.scala
- zmessaging/src/test/scala/com/waz/model/UserInfoSpec.scala
Bug: wireless guests are not displayed as wireless. They have no expiration time and it's possible to connect to them.
The reason is that `expires_at`, which is used to distinguish if a user is a guest user, is overwritten with `None` when updating the `UserData`.
- Fix `expires_at` field in `UserData` being overwritten with `None` when applying `UserInfo` to `UserData`
- Removed code duplication in the `apply` method of `UserData`
- Added tests to cover `UserData` update from UserInfo
- The new test showed that `teamId` was also not correctly initialized when creating `UserData` from `UserInfo`. This was fixed too by removing code duplication
- Added new unit tests for `UserData` and `UserInfo`
- Manually tested on device before and after: now wireless users are displayed correctly
> Fix `expires_at` not being preserved when updating `UserData`

- build.sbt
There are several types of builds done in slightly different configurations and it could simplified to be more consistent. In addition the version numbers are set to different strings depending on Jenkins environment variables which makes it specific to the CI setup we have.
The table summarises the current situation. The proposed changes for version numbers are outlined
Branch | Version (current) | Version (proposed) | Debug | Bintray repo |
-- |	-- | -- | -- | -- | 
master | `141.0.512` | `141.0.512` | ❌ | Release
develop | `141.2237` | `141.0.512-DEV` | ✅ | Snapshot
PR | `141.768-PR` | `141.0.512-PR` | ✅ | Snapshot
Local | `141-SNAPSHOT` | `141.0.0-DEV` | ✅ | N/A
Also the way we build the project is changed slightly to make it less coupled to Jenkins:
* Passing the type of build as …
> Simplified build configuration

- build.sbt
After #502 when doing `sbt publishM2` twice we get an error that version already exists and cannot be overwritten.
The version for local build was changed from `141-SNAPSHOT` to `141.0.0-DEV`. Apparently versions with suffix `-SNAPSHOT` are treated slightly differently and it's possible to overwrite them.
Only `dev` will have `-DEV` suffix and local builds have `-SNAPSHOT`.
Tried running `sbt publishM2` twice.
> Building: added separate case for local builds

- zmessaging/src/main/scala/com/waz/content/Preferences.scala
- zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
- zmessaging/src/main/scala/com/waz/model/AccountDataOld.scala
- zmessaging/src/main/scala/com/waz/model/Handle.scala
- zmessaging/src/main/scala/com/waz/model/SearchQuery.scala
- zmessaging/src/main/scala/com/waz/model/UserData.scala
- zmessaging/src/main/scala/com/waz/model/UserPermissions.scala
- zmessaging/src/main/scala/com/waz/service/AccountsService.scala
- zmessaging/src/main/scala/com/waz/service/Timeouts.scala
- zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
- zmessaging/src/main/scala/com/waz/service/teams/TeamsService.scala
- zmessaging/src/main/scala/com/waz/sync/client/TeamsClient.scala
- zmessaging/src/main/scala/com/waz/sync/handler/TeamsSyncHandler.scala
- zmessaging/src/main/scala/com/waz/sync/handler/UsersSyncHandler.scala
- zmessaging/src/test/scala/com/waz/service/UserSearchServiceSpec.scala
- zmessaging/src/test/scala/com/waz/sync/client/TeamsClientSpec.scala
- zmessaging/src/test/scala/com/waz/sync/handler/TeamsSyncHandlerSpec.scala
The functionality for filtering out from the user search results which should not be visible for partners. The results visible for standard team members are also slightly changed, taking into account that some of the results are partners.
For details please refer to the documentation:
https://github.com/wearezeta/documentation/blob/master/topics/teams/use%20cases/clients/101-search-for-partners.md
> feat: Users other than `self` should have the permission field in the user data

- zmessaging/src/test/scala/com/waz/service/UserSearchServiceSpec.scala
The previous code required the test author to repeat some information in functions call, that could actually be inferred from previous parameters. It was easy to make a mistake and pass in a different information the second time, leading to unexpected test results.
I removed the redundancy, requiring the test author to repeat the following information only once:
- query
- who is the self user
I also removed the need to pass the role for the user. Now it's inferred automatically from the user id.
> refactor: remove some redundancy in UserSearchServiceSpec

- zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
- zmessaging/src/test/scala/com/waz/service/UserSearchServiceSpec.scala
A fix to [AN-6074](https://wearezeta.atlassian.net/browse/AN-6074)
The directory search did not filter out wireless users from the results.
Added a check for `expiredBy` which indicates that the user is wireless.
A unit test was added.
> fix: Wireless users should not appear in a search

- zmessaging/src/main/scala/com/waz/log/BufferedLogOutput.scala
After disabling global logging, few logs statements still printed to log files.
We do explicit `flush` before clearing `BufferedLogOutput`
> Flush logs before cleaning in BufferedLogOutput.

- zmessaging/src/main/scala/com/waz/repository/FCMNotificationStatsRepository.scala
- zmessaging/src/main/scala/com/waz/repository/FCMNotificationsRepository.scala
- zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
- zmessaging/src/test/scala/com/waz/repository/FCMNotificationsRepositorySpec.scala
- zmessaging/src/test/scala/com/waz/service/FCMNotificationStatsServiceSpec.scala
If there are bugs in how we delete the timestamps of notifications, then we might end up with an ever-growing table of timestamps. To avoid this, a check is added when we write the final timestamp to delete the oldest row over a limit. This limit has been set to 1000 rows as this should be enough for even extreme situations.
> Add trimming in case of bugs where notification stats aren't processed

- zmessaging/src/main/scala/com/waz/content/Preferences.scala
Public builds had logging enabled by default, instead of this being off.
This was caused due to us reading a boolean variable set in BuildConfig which is always set to true. This is because it's generated by the Android build tools, presumably as a result of our NDK build, but this has nothing to do with the Sync Engine build proper, so we shouldn't use it.
Use a different file which we manually generate in build.sbt to determine debug status
This was tested manually.
> fix: Production builds were set to "debug"

- zmessaging/src/main/scala/com/waz/model/UserData.scala
- zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
- zmessaging/src/main/scala/com/waz/service/UserService.scala
- zmessaging/src/main/scala/com/waz/sync/client/UserSearchClient.scala
We want to remove our own custom JSON (de)serialization and instead rely on **Circe**. This is a small step toward that goal.
The deserialization code in `UserSearchClient` has been replaced with auto derived circe json objects.  We define a response object for each backend response that we expect. In this case `UserSearchResponse` and `ExtractHandleResponse`. These objects reflect the structure of the response payload (but we only include keys that we're interested in). Simply by defining these objects, deserialization handled for us.
The model objects extracted from these responses are defined in the domain layer, to maintain separation. In this case, `UserSearchEntry` has been moved from `UserSearchClient` to `UserSearchService`.
> Refactor: json user search client

- zmessaging/src/main/scala/com/waz/content/Preferences.scala
- zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
- zmessaging/src/main/scala/com/waz/service/push/NotificationService.scala
- zmessaging/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
- zmessaging/src/test/scala/com/waz/service/notifications/NotificationServiceSpec.scala
Depending on the availability status we restrict what notifications (if any) are pushed to UI to be displayed.
I had to add new requirements to the way `NotificationService` figures out what notifications to push to UI, and since the logic became a bit complex for one long expression, I decided to break it down in a series of i`f/else`s for better readability.
Also, I added unit tests, and refactored `NotificationServiceSpec`, putting code common to most unit tests in a private method.
Two new user preferences are going to be used in UI for displaying / not-displaying popups warning about the new functionality.
> feat: Status Notifications

- zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
- zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
There is an issue where occasionally we create multiple conversations instead of just one when opening the conversation with a user for the first time.
> refactor: Add logging to debug dup conv creation

- zmessaging/src/main/scala/com/waz/content/Preferences.scala
- zmessaging/src/main/scala/com/waz/model/Availability.scala
This is a part of the fix to https://wearezeta.atlassian.net/browse/AN-6200
We need to display a warning popup for each availability status, and then allow the user
to click "Never show that (one particular) warning again".
Instead of keeping a separate flag for each one I decided to keep one bitmask. This solution may also come in handy in the future, in other situations when we have to handle availability statuses.
> fix: Adding a bitmask to the Availability status, to help handle statuses in UI

- zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
("mentions & replies" really means "mentions, replies & calls")
When we introduced mentions & replies, we added a possibility to filter notifications from a conversation, so the user was notified only when a message in the conversation was a reply or a mention. For some reason, probably connected to the fact that notifications about call work differently in iOS and Android, and we didn't catch that it would be a problem in Android, the filter ignored calls. This was caught only now, when the decision tree for notifications was updated because now notifications are also affected by the availability status. 
This PR changes the filter so that calls also go through if the conversation is set to "Mentions & Replies only". Basically, this mode means "Mentions, Replies & Calls".
> fix: If the conversation is set to mentions & replies, a call should also go through

- zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
- zmessaging/src/main/scala/com/waz/model/MuteSet.scala
- zmessaging/src/test/scala/com/waz/model/MuteSetSpec.scala
When the user changes the conversation muted status, the change is propagated to his or her other devices. The id of the status was inconsistent between Android and other platform, causing a bug that if the status was set to `Mentions & Replies` on Android, the change was interpreted  as a different status on Web and iOS. 
This PR provides a migration and a small change to the functionality. Nost of the fix is already on develop, together with the Status Notifications feature.
> fix: Fixes an inconsistency in how a change of the conversation muted status is reported

- zmessaging/src/main/scala/com/waz/model/Event.scala
- zmessaging/src/main/scala/com/waz/service/conversation/ConversationsContentUpdater.scala
- zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
The `muteTime` property was set to a time in the past, which on iOS was interpreted as that the event has already taken place and was ignored.
Fixes https://wearezeta.atlassian.net/browse/AN-6210
> fix: Fixes an inconsistency in how a change of the Conversation Muted status is reported between Android and other platforms

- build.sbt
- zmessaging/src/main/scala/com/waz/znet2/WebSocketFactory.scala
- zmessaging/src/test/scala/com/waz/znet2/OkHttpWebSocketSpec.scala
Same as #534 (see that PR for detailed description) with the only difference relating to tests: this removes the (unstable, not well-maintained) `"io.fabric8" "mockwebserver" `. Instead, this uses akka-http's real websocket server in the tests. 
Do you prefer this over #534  @marcoconti83 @CalumMcCall ?
> Fix websocket behaviour (and rewrite tests)

- zmessaging/src/main/scala/com/waz/model/MessageData.scala
- zmessaging/src/main/scala/com/waz/znet2/OkHttpUserAgentInterceptor.scala
Several links no longer generate link previews. These include Facebook, Twitter, and Spotify.
When we detect a link in a sent message, we make a GET request to search the body for open graph tags. In the request we specify a desktop user agent so that the response contains the tags (mobile versions of sites often do not contain the tags).
However... in https://github.com/wireapp/wire-android-sync-engine/pull/470 we introduced a request interceptor to set a custom user agent. This would overwrite any existing user agent specified in the header at an earlier stage (such as when the request is created).
When intercepting the request, only set the custom user agent if one does not already exist.
Manually tested.
I found some duplicated code so I removed that too.
> fix: broken link previews

- zmessaging/src/main/scala/com/waz/model/MessageData.scala
There should be no preview displayed for a markdown link. Unfortunately, we parse the message data in SE and here we prepare links to be displayed with previews, but only much later in UI we apply markdown. When the parsed link part of the message is displayed in UI we no longer know that originally it was a markdown link, and it's difficult to find it out at that point.
Instead, I decided to ignore markdown links during the parsing in SE. It's a bit hacky (now even if there
was no markdown handling in UI we would still not display the preview), but it's much easier and faster.
> fix: Ignore markdown links

- zmessaging/src/main/scala/com/waz/content/Preferences.scala
This PR changes the default for the websocket foreground service to off, since it should only be required in specific circumstances. Check the [UI PR](https://github.com/wireapp/wire-android/pull/2169) for a detailed explanation of the issue.
> feat: Change default for ws service pref to off

- zmessaging/src/main/scala/com/waz/log/LogShow.scala
- zmessaging/src/test/scala/com/waz/log/ZLog2Spec.scala
Collections were not being properly logged.
The obfuscation function was not being applied before joining the elements into a string.
Apply the obfuscation function before joining the elements.
Added a single unit test checking the outputs of logging a collection.
> Fix: traversable show

- zmessaging/src/main/scala/com/waz/content/ConvMessagesIndex.scala
- zmessaging/src/main/scala/com/waz/content/MessagesStorage.scala
- zmessaging/src/main/scala/com/waz/model/MessageData.scala
- zmessaging/src/main/scala/com/waz/service/ConnectionService.scala
- zmessaging/src/main/scala/com/waz/service/EventPipeline.scala
- zmessaging/src/main/scala/com/waz/service/GenericMessageService.scala
- zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
- zmessaging/src/main/scala/com/waz/service/conversation/ConversationOrderEventsService.scala
- zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
- zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
- zmessaging/src/main/scala/com/waz/service/messages/MessageEventProcessor.scala
- zmessaging/src/main/scala/com/waz/service/messages/MessagesContentUpdater.scala
- zmessaging/src/main/scala/com/waz/service/push/PushService.scala
- zmessaging/src/main/scala/com/waz/sync/SyncRequestService.scala
- zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
- zmessaging/src/main/scala/com/waz/sync/queue/SyncExecutor.scala
- zmessaging/src/main/scala/com/waz/sync/queue/SyncScheduler.scala
- zmessaging/src/main/scala/com/waz/utils/CachedStorageImpl.scala
- zmessaging/src/main/scala/com/waz/utils/EventProcessingQueue.scala
All logs starting with 'SYNC' should be treated as temporary. They were added in order to investigate why sometimes the app gets stuck when syncing on initialization. They can be removed when the bug is fixed.
Apart form adding logs I made two changes:
1. In `Message contentUpdater.addContentMessages` I changed `msgs.mapValues` to `msgs.map`.  `mapValues` does not really map the values - it provides a wrapper with a mapping function, and the mapping takes places only when the value is accessed which may have side-effects. I'd like to gradually remove `mapValues` form the code.
2. In `CachedStorage` I added a functionality which blocks streams: `onAdded`, `onUpdated`, and `onDeleted`. During sync we add, update, and delete a lot of data. It might make sense to postpone sending events about …
> chore: Logs for better investigation of the sync process

- zmessaging/src/test/scala/com/waz/FilesystemUtils.scala
- zmessaging/src/test/scala/com/waz/cache2/LruFileCacheSpec.scala
- We create test directories for certain types of tests, such as
LRUFileCacheSpec, but we use milliseconds to ensure uniqueness
of the directory name, which wasn't always the case as the method
is called frequently. This commit adds a counter to ensure dir names
are unique.
- This addresses AN-6249, thus also fixing the flaky LRUCache tests
> fix: LRUFileCacheSpec failing due to directory name conflicts

- zmessaging/src/test/scala/com/waz/model/EventSpec.scala
There were some tests that were disabled pending fixes to base64, which was completed a while ago, so we should re-enable or remove them. [See here](https://wearezeta.atlassian.net/browse/AN-6248)
The calling test is no longer relevant, since we decode call events from a GenericMessage instead inside `OtrServiceImpl.scala`, the other test was re-enabled.
> refactor: uncomment out eventspec tests

- zmessaging/src/main/scala/com/waz/model/Event.scala
- zmessaging/src/test/scala/com/waz/model/EventSpec.scala
This commit adds missing support for updating local read receipt setting when it's changed on another client. This fixes a [related issue](https://wearezeta.atlassian.net/browse/AN-6110) where the popup notifying of the change was not displaying.
I think this small detail was simply left out during implementation of this feature
The missing event type decoding has been implemented.
Manual testing has been done. The option was toggled using a web client whilst the correct behaviour was observed on the device.
> fix: read receipts not updating

- zmessaging/src/main/scala/com/waz/model/TeamData.scala
- zmessaging/src/main/scala/com/waz/sync/client/TeamsClient.scala
- zmessaging/src/test/scala/com/waz/sync/client/TeamsClientSpec.scala
The app would sometimes get stuck in a sync loop. When syncing team data, the response from the backend would fail to decode. This caused the team sync to fail, but the request would continuously retry.
The Circe json parser would fail to decode the response object from the backend. We use auto derivation to encode/decode json objects. In order for it to work, we must provide a data class the exactly models the json response object (though, only for the properties that we care about). 
In this specific case, the `TeamData` object is being used to model a response, however it contains inconsistent property names and data types for those properties. 
Provide a `TeamDataResponse` object to specifically model the response. Then convert the response object to a `TeamData` instance once …
> Fix: team sync

- zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
If the app is upgrade from a version built around 7th June, the app would launch to a black screen and it would be impossible to recover.
The assets refactoring contained a database migration which unfortunately duplicated an SQL command already existing in the migration from `ZMessageDB` version 113 to 114. When the migration from 120 to 121 (for assets) occurred, it would fail and subsequently the database is left in an inconsistent state. Unfortunately this is not recoverable.
Remove the duplicated command.
Tested manually.
> Fix: Remove duplicate SQL command

- zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
- zmessaging/src/main/scala/com/waz/sync/handler/ConversationsSyncHandler.scala
Fixes AN-6162. The issue is that opening a conversation with a bot always failed, although I did get it to work occasionally in testing. It's possible this PR will also address the duplicate conversation issue we were having, since everytime creating a conv with a bot fails, we create an empty conversation which is never used again.
The cause was that `ConversationsService.updateConversations` doesn't handle updating the remoteId properly. This is because despite the method's name, it doesn't handle updating conversations in the general case. It relies on being able to find the conversation through various means, but none of these work in the case of creating conversations for bots, since those conversations have random or duplicate Ids, in the case of the `ConvId` and `RConvId` …
> fix: opening convs with bots works again

- zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
- zmessaging/src/main/scala/com/waz/service/conversation/NameUpdater.scala
The logs were getting spammed full of "forceNameUpdate" messages. See [AN-6259](https://wearezeta.atlassian.net/browse/AN-6259).
Conversations with only the self user were not getting their generated name set correctly, resulting in attempts to update their name every time the conversation list was scrolled. This was due to the user list being empty after the self user was filtered out, resulting in an empty name, which would generate the `forceNameUpdate` again later.
A check was added for the case where the conversation members are only the self user. In this case, a  default name is used.
This was tested manually, and the logs are now cleaner. A unit test is unfortunately not possible in this case, as the generated name is provided inside a closure as an argument to …
> fix: name updating for memberless conversations

- zmessaging/src/main/scala/com/waz/model/UserData.scala
- zmessaging/src/main/scala/com/waz/model/UserInfo.scala
- zmessaging/src/main/scala/com/waz/model/sync/SyncRequest.scala
- zmessaging/src/main/scala/com/waz/service/UserService.scala
- zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
- zmessaging/src/main/scala/com/waz/sync/handler/UsersSyncHandler.scala
- zmessaging/src/main/scala/com/waz/utils/JsonDecoder.scala
- zmessaging/src/test/scala/com/waz/Generators.scala
- zmessaging/src/test/scala/com/waz/utils/PasswordValidatorSpec.scala
A fix to an assets bug: A change in the profile picture was not propagated to other users.
In `UsersSyncHandler.postSelfPicture` the assetId was not retrieved correctly.
On top of that updating the  picture used different logic than other self updates: name, availability, handle, etc. I decided to change the way updating the picture works so it matches more closely the rest.
1. Create a conversation with at least one device on Android.
2. On the Android device, change the profile picture.
3. On the other device, the chathead of the user should change.
I removed a method used for old (V2) pictures handling. It was not used anymore.
> fix: An update of the profile picture is propagated to other users

- zmessaging/src/main/scala/com/waz/service/messages/MessageEventProcessor.scala
- zmessaging/src/test/scala/com/waz/service/MessageEventProcessorSpec.scala
A fix to a regression bug.
fixes: https://wearezeta.atlassian.net/browse/AN-6279
When a user from another platform sent a reply to their own message, Android displayed an error message instead. 
The bug was regression. It occured after the new assets were merged. In changes to `MessageEventProcessor` a call to the `checkReplyHashes` method was deleted. The call has to be there, because we need to recreate locally the hash of the quoted message. If not, the hashes may differ and the quoted message will be treated as invalid (look to the specs of of the replies feature for details).
The fix simply adds back the call to `checkReplyHashes`.
Preconditions: User1 is on Android, User2 is on webapp, connected
1) Open 1:1 with User2
2) User 2 sends a message (text, audio etc)
3) User 2 replies on …
> fix: Self-replies don't show up on Android

- zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
Back in April we changed the name of the user preference `ShouldSyncUsers`. The migration code for new assets specified that after the migration the users shoulds be synced, so that their profile pictures will now use new assets. The bug was that the code still used the old name of the preference.
It should be save to simply modify the migration. If someone experiences the bug in Internal (they should) they just have to perform full sync.
fixes: https://wearezeta.atlassian.net/browse/AN-6287
> fix: Sync users after the migration to new assets (no profile pictures)

- zmessaging/src/main/scala/com/waz/service/assets2/AssetService.scala
- zmessaging/src/test/scala/com/waz/service/assets2/AssetServiceSpec.scala
1. Send a video in a conversation.
2. Click on the video to play it.
3. The video fails to play the first time. It works the second time.
The reason of the bug was in that before playing the video we first check the sha (for security reasons). We calculate the sha by loading the whole input stream. The stream should be reset if the sha is valid, so it can be read again when we copy the video in order to play it afterwards.  And if the sha is invalid, the stream should be closed. Instead, we tried to open it for the second time if the sha comparison was successful.
While working on this bug I also simplified the code around it - it was difficult to spot it at first.
> fix: The sender's device fails to play the video the first time

- zmessaging/src/main/scala/com/waz/service/push/WSPushService.scala
What's new in this PR?
iOS clients append the "/await" path to websocket uris automatically. On Android we need to add them ourselves. This was causing issues with using one config for both Android/iOS, so this PR changes the Android client to be able to accept both kinds of URIs, and append the required path when needed.
Fixes [AN-6312](https://wearezeta.atlassian.net/browse/AN-6312)
> fix: accept websocket uri without path

- zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
- zmessaging/src/main/scala/com/waz/service/media/GoogleMapsMediaService.scala
- zmessaging/src/main/scala/com/waz/sync/client/GoogleMapsClient.scala
- zmessaging/src/test/scala/com/waz/service/media/GoogleMapsMediaServiceSpec.scala
- zmessaging/src/test/scala/com/waz/sync/client/GoogleMapsClientSpec.scala
After the assets refactoring, the code used to load map previews died. This PR repurposes this code to help facilitate fetching map previews.
The map previews can now be loaded using Glide by simply providing a url. As such, we no longer have to return an `AssetData`, rather a `URI` now suffices.
We couldn't make the direct request to google due to privacy issues, so I've reverted back to using the proxy. As a result, I've changed `GoogleMapsClient` to make the request to the backend as we do with other clients. `GoogleMapsMediaService` is responsible for invoking the request, and returns an `InputStream` containing the image data. This stream will be used in the UI to load via _Glide_.
> Fix: google map previews

- zmessaging/src/main/scala/com/waz/sync/client/VersionBlacklistClient.scala
- [AN-6258](https://wearezeta.atlassian.net/browse/AN-6258)
- This PR fixes the blacklist url parsing code, which was adding a suffix unconditionally, causing the url to become invalid and blacklist loading to fail
Testing both with and without the "/android" prefix was tested manually.
> fix: version blacklist uri

- zmessaging/src/main/scala/com/waz/content/Preferences.scala
This PR simply adds a flag to the global preferences. It stores whether the device was ever rooted while Wire was running.
**This flag is used ONLY in the case that this feature has been enabled. By default, this feature is disabled. Furthermore, it can only be enabled for custom builds.**
> Feature: add root detected flag to global preferences

- zmessaging/src/main/scala/com/waz/content/Preferences.scala
Soon we will discontinue support for Android 4. This flag will be used to decide if we should present a dialog to warn the user.
> Add flag to global preferences for warning Android 4 users

- zmessaging/src/main/scala/com/waz/content/MessagesStorage.scala
- zmessaging/src/main/scala/com/waz/model/MessageData.scala
- zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
- Fixes [AN-6293](https://wearezeta.atlassian.net/browse/AN-6293)
- This PR introduces an additional step to delete unsent(failed, pending) messages when clearing a conversation.
Since (failed, pending) messages haven't been synced yet, they weren't being cleared, as the `lastEventTime` is used to set the cleared time, and this is only updated after a given message has been synced with the backend.
Since changing `lastEventTime` would result in other clients potentially losing messages, it was decided to simply delete all unsent messages when clearing, since this most closely matches what the user would expect
It was tested manually, and clearing the conversation now deletes failed messages as expected
> fix: clearing conversations now clears failed msgs

- build.sbt
`ZLog` was removed from the `macrosupport` module in https://github.com/wireapp/wire-android-sync-engine/pull/505. In the UI project, `macrosupport` is a transitive dependency, however it the UI project still had references to `ZLog` even though it still successfully compiled.
The `macrosupport` version was bumped in https://github.com/wireapp/wire-android-sync-engine/pull/513 from 3.1 to 3.2. This PR was merged on June 7th. On Bintray, `macrosupport` version 3.2 was published on February 19th. I think what went wrong here is that the version published on Bintray was actually built before `ZLog` was removed, and somehow the version numbers went out of sync. Also, it seems that `macrosupport` was never built and release on Bintray since February, so all recent changes have been dormant.
I …
> Fix: bump macrosupport version

- zmessaging/src/main/scala/com/waz/content/Preferences.scala
- [AN-6323](https://wearezeta.atlassian.net/browse/AN-6323)
- This PR introduces a new user pref to track whether to hide screen
content in the task switcher
- The method used in fact blocks all screenshots, including the ones
taken for the task switcher
> feat: add pref to hide screen content

- zmessaging/src/main/scala/com/waz/content/TeamsStorage.scala
- zmessaging/src/main/scala/com/waz/db/ZGlobalDB.scala
- zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
- zmessaging/src/main/scala/com/waz/model/Event.scala
- zmessaging/src/main/scala/com/waz/model/TeamData.scala
- zmessaging/src/main/scala/com/waz/service/teams/TeamsService.scala
- zmessaging/src/main/scala/com/waz/sync/client/TeamsClient.scala
- zmessaging/src/main/scala/com/waz/utils/CirceJSONSupport.scala
- zmessaging/src/test/scala/com/waz/sync/client/TeamsClientSpec.scala
- zmessaging/src/test/scala/com/waz/sync/handler/TeamsSyncHandlerSpec.scala
This PR includes changes to `TeamData` required to display the team logo. Specifically, I have changed the type for `icon` from `RAssetId` to `AssetId` to be more aligned with the new way we process assets. Additionally, I've removed the `icon_key` property since team logos are now considered to be public assets, and therefore the key is no longer needed.
These changes required a migration for both the global and user databases. The migration in the user database is to simply switch a flag so that the team will sync on upgrade. The migration in the global database is to drop the column for `icon_key`.
I manually tested the database migration, all is fine and no black screen of death 😄
> Feature: team logo

- zmessaging/src/main/scala/com/waz/content/Preferences.scala
This PR simply adds a global preference for enabling app lock. It will be used in the UI project to add a preference in the app settings. It is a global preference because the app lock is not a per-account feature.
> Feature: add global preference for app lock

- zmessaging/src/main/scala/com/waz/service/messages/MessageEventProcessor.scala
- zmessaging/src/main/scala/com/waz/service/otr/VerificationStateUpdater.scala
- zmessaging/src/test/scala/com/waz/service/MessageEventProcessorSpec.scala
With new assets the message data was enlarged with a new field, `assetId: Option[AssetId]`.
So, instead of looking through assets for those having the given messageId, we use the fact
that we display at most one asset per message and we can simply store its id in the message.
`MessageEventProcessor` was modified, so that now it looks for assets and sets `assetId` when
creating `MessageData`. However, that part was broken for ephemeral messages: if a message
was ephemeral and having an asset, it was recognized first as having an asset, but then
the code failed to set the asset's id, because the type of the event was invalid.
I suspect the reason for that bug was that `MessageEventProcessor` became very complex. A lot
of changes was made to it during the last years, and it was never …
> fix: Ephemeral assets are not displayed
