wireapp/wire-android-sync-engine

- zmessaging/src/main/java/com/waz/api/EphemeralExpiration.java
> [AN-4606] Updated ephemeral expiration values

- zmessaging/src/main/scala/com/waz/service/messages/MessagesContentUpdater.scala
Ticket: https://wearezeta.atlassian.net/browse/AN-4619
> [AN-4619] Duplicate system messages

- zmessaging/src/main/scala/com/waz/service/conversation/UnarchivingEventProcessingStage.scala
Ticket: https://wearezeta.atlassian.net/browse/AN-4630
> [AN-4630] Ephemeral messages unarchive conversations

- tests/unit/src/test/scala/com/waz/sync/client/OpenGraphClientSpec.scala
- zmessaging/src/main/scala/com/waz/sync/client/OpenGraphClient.scala
Some links weren’t showing preview even though they have the necessary meta tags.
Tickets: https://wearezeta.atlassian.net/browse/AN-4302
> Link preview

- zmessaging/src/main/java/com/waz/api/Self.java
- zmessaging/src/main/java/com/waz/api/User.java
- zmessaging/src/main/scala/com/waz/api/Usernames.scala
- zmessaging/src/main/scala/com/waz/api/impl/Self.scala
- zmessaging/src/main/scala/com/waz/api/impl/User.scala
- zmessaging/src/main/scala/com/waz/api/impl/Usernames.scala
Empty methods on the sync engine to start developing the UI side.
> Empty methods for usernames

- tests/unit/src/test/scala/com/waz/api/impl/UsernamesSpec.scala
- zmessaging/src/main/java/com/waz/api/Self.java
- zmessaging/src/main/java/com/waz/api/UsernameValidationError.java
- zmessaging/src/main/scala/com/waz/api/Usernames.scala
- zmessaging/src/main/scala/com/waz/api/ZMessagingApi.scala
- zmessaging/src/main/scala/com/waz/api/impl/Self.scala
- zmessaging/src/main/scala/com/waz/api/impl/Usernames.scala
- zmessaging/src/main/scala/com/waz/api/impl/ZMessagingApi.scala
Ticket: https://wearezeta.atlassian.net/browse/AN-4683
> [AN-4683] Username rules validation

- actors/base/src/main/scala/com/waz/provision/ActorMessage.scala
- actors/base/src/main/scala/com/waz/provision/DeviceActor.scala
PS: we call it user name in actor
> Add actor to support for updating unique user name

- tests/integration/src/test/scala/com/waz/tracking/AssetTrackingSpec.scala
- tests/integration/src/test/scala/com/waz/tracking/TrackingEventsSpec.scala
- tests/unit/src/test/scala/com/waz/service/push/PushTrackingServiceSpec.scala
- zmessaging/src/main/scala/com/waz/api/TrackingEventsHandler.scala
- zmessaging/src/main/scala/com/waz/api/impl/ConnectionsSearch.scala
- zmessaging/src/main/scala/com/waz/api/impl/Usernames.scala
- zmessaging/src/main/scala/com/waz/service/HandlesService.scala
- zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
- zmessaging/src/main/scala/com/waz/service/tracking/TrackingEventsService.scala
- zmessaging/src/main/scala/com/waz/sync/client/HandlesClient.scala
- zmessaging/src/main/scala/com/waz/sync/handler/HandlesSyncHandler.scala
Also search connections by handle
> Add tracking callback to handle validation

- zmessaging/src/main/scala/com/waz/api/impl/ConnectionsSearch.scala
- zmessaging/src/main/scala/com/waz/api/impl/search/ConversationSearchResult.scala
- zmessaging/src/main/scala/com/waz/api/impl/search/Search.scala
- zmessaging/src/main/scala/com/waz/content/ConversationStorage.scala
- zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
- zmessaging/src/main/scala/com/waz/db/migrate/ConversationDataMigration.scala
- zmessaging/src/main/scala/com/waz/db/migrate/ConversationMembersMigration.scala
- zmessaging/src/main/scala/com/waz/db/migrate/UserDataMigration.scala
- zmessaging/src/main/scala/com/waz/model/ConversationData.scala
- zmessaging/src/main/scala/com/waz/model/Handle.scala
- zmessaging/src/main/scala/com/waz/model/SearchQuery.scala
- zmessaging/src/main/scala/com/waz/model/UserData.scala
- zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
- zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
- zmessaging/src/main/scala/com/waz/sync/client/UserSearchClient.scala
Groups can be found by the handles of their users.
Added indexes to the tables used in the group search to improve the performance of the query.
> Group search improvements

- actors/base/src/main/scala/com/waz/provision/DeviceActor.scala
Fix actor about to send image asset by File transfer.
Test with .txt , image file, and video file
> Actor: Fix send file for image asset

- zmessaging/src/main/scala/com/waz/api/MessageFilter.scala
- zmessaging/src/main/scala/com/waz/content/ConvMessagesIndex.scala
- zmessaging/src/main/scala/com/waz/content/MessagesStorage.scala
- zmessaging/src/main/scala/com/waz/model/MessageData.scala
> Add the possibility of filtering the messages in a cursor

- tests/utils/src/main/scala/com/waz/testutils/package.scala
Ref : https://github.com/jruby/jruby/issues/4101
Change the JCE configuration
> RemoteActor: Update JCE configuration JDK 8u102

- actors/base/src/main/scala/com/waz/provision/DeviceActor.scala
The reason is : withConv and getConv doesn't wait until the conversation exist. If I do SendFile after Login immediately,  and if I do getConv or withConv, the actor will be failed.
> DeviceActor: Use whenConversationExist instead of withConv or getConv

- zmessaging/src/main/scala/com/waz/sync/client/OpenGraphClient.scala
Added handling for connection error and proper fallback for unexpected responses
> [AN-4867] Fix OpenGraphClient error handling.

- zmessaging/src/main/scala/com/waz/content/ConvMessagesIndex.scala
- zmessaging/src/main/scala/com/waz/model/MessageData.scala
The lastSentMessage signal wasn't updated, hence the system message for unverified conversation was mis-placed.
(Related to #17 )
> [AN-4657][AN-4879] Show unverified message in correct position

- zmessaging/src/main/scala/com/waz/znet/ClientWrapper.scala
Changed domain check to not rely only on SAN list, as this may not always be
present.
This prevents MITM attack in case where attacker was able to install malicious certificate
on client device or compromised some Certificate Authority. In that case attacker
would be able to create certificate with unexpected SAN list and thus circumvent
our certificate pinning.
This will not be possible anymore.
>  Drop dependency on SAN list check only for hostname verification.

- zmessaging/src/main/scala/com/waz/service/NetworkModeService.scala
> Re-register broadcast receiver

- zmessaging/src/main/scala/com/waz/service/images/ImageAssetGenerator.scala
What do you think @deanrobertcook?
> Use same cache key for scaled images

- tests/integration/src/test/scala/com/waz/messages/ContentSearchSpec.scala
Add integration test for Message search
> Text search integration test

- zmessaging/src/main/scala/com/waz/model/MessageData.scala
- zmessaging/src/main/scala/com/waz/service/media/RichMediaContentParser.scala
- zmessaging/src/main/scala/com/waz/service/media/SpotifyMediaService.scala
- zmessaging/src/main/scala/com/waz/sync/client/SoundCloudClient.scala
- zmessaging/src/main/scala/com/waz/sync/client/SpotifyClient.scala
- zmessaging/src/main/scala/com/waz/sync/client/YouTubeClient.scala
- zmessaging/src/main/scala/com/waz/znet/AsyncClient.scala
- zmessaging/src/main/scala/com/waz/znet/ZNetClient.scala
Adding play.spotify.com to the list of known domains in order for [AN-5062] to work with Spotify links.
Changing how the known domains are recognized from the exact match to that it is sufficient for the domain name to be a substring.
> Adding play.spotify.com to the list of known domains

- tests/mocked/src/test/scala/com/waz/mocked/MockedClientSuite.scala
- tests/unit/src/test/scala/com/waz/content/MessagesCursorSpec.scala
- tests/unit/src/test/scala/com/waz/db/ZMessagingDBSpec.scala
- zmessaging/src/main/scala/com/waz/api/ContentSearchQuery.scala
- zmessaging/src/main/scala/com/waz/api/impl/MessagesList.scala
- zmessaging/src/main/scala/com/waz/content/ConvMessagesIndex.scala
- zmessaging/src/main/scala/com/waz/content/MessageIndexStorage.scala
- zmessaging/src/main/scala/com/waz/content/MessagesCursor.scala
- zmessaging/src/main/scala/com/waz/db/Dao.scala
- zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
- zmessaging/src/main/scala/com/waz/db/migrate/MessageDataMigration.scala
- zmessaging/src/main/scala/com/waz/db/package.scala
- zmessaging/src/main/scala/com/waz/model/MessageContentIndexDao.scala
- zmessaging/src/main/scala/com/waz/model/MessageData.scala
Couple fixes for scrolling performance in conv and in search results.
Please see comments in individual commits. Feel free to apply only selected commits if you don't like any changes.
There is related PR for corresponding changes in UI, it has to be merged together as some API was changed.
> Scrolling performance improvements

- zmessaging/src/main/scala/com/waz/model/Mime.scala
- zmessaging/src/main/scala/com/waz/service/messages/MessagesContentUpdater.scala
- zmessaging/src/main/scala/com/waz/service/messages/MessagesService.scala
Ticket: https://wearezeta.atlassian.net/browse/AN-4805
> [AN-4805] Add WebM mime

- zmessaging/src/main/scala/com/waz/api/impl/ErrorsList.scala
- zmessaging/src/main/scala/com/waz/sync/otr/OtrSyncHandler.scala
> [AN-5098][AN-5105] Degraded fix

- zmessaging/src/main/scala/com/waz/service/call/CallingService.scala
Ticket: https://wearezeta.atlassian.net/browse/AN-5139
> [AN-5139] Sets mute state after call established

- zmessaging/src/main/scala/com/waz/utils/WakeLock.scala
- zmessaging/src/main/scala/com/waz/zms/WebSocketService.scala
Added couple logs for websocket service.
> Websocket logs

- zmessaging/src/main/scala/com/waz/service/push/PushService.scala
- zmessaging/src/main/scala/com/waz/utils/WakeLock.scala
- zmessaging/src/main/scala/com/waz/zms/FutureService.scala
Changed to acquire async wakelock to actually cover notification processing.
Added a bit more logging to wake locks and bg services.
> Fix wakelock in PushService notification processing.

- tests/unit/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
- zmessaging/src/main/scala/com/waz/service/call/AvsV3.scala
- zmessaging/src/main/scala/com/waz/service/call/Calling.scala
- zmessaging/src/main/scala/com/waz/service/call/DefaultCallingService.scala
* Required AVS 3.4.67 or greater
> Updated AVS API and added a test for AnsweredElsewhere

- zmessaging/src/main/scala/com/waz/service/ConnectionService.scala
- zmessaging/src/main/scala/com/waz/sync/handler/ConnectionsSyncHandler.scala
Updated unit tests coming soon…
> Event handling after connection request including last time event update

- zmessaging/src/main/scala/com/waz/utils/NameParts.scala
Ticket: https://wearezeta.atlassian.net/browse/AN-5237
> [AN-5237] Check if the input string is empty

- zmessaging/src/main/scala/com/waz/content/MessagesCursor.scala
There are reports with timeouts on window prefetches:
https://wearezeta.atlassian.net/browse/AN-5126
Although uncertain if those are related to the missing messages.
> Catch timeouts

- zmessaging/src/main/scala/com/waz/service/conversation/UnarchivingEventProcessingStage.scala
Receiving a location neither. Fixed.
> [AN-5153] Receiving AssetV3 image does not restore deleted conversation

- build.sbt
- project/SharedSettings.scala
> Update Android support lib for FCM and add google maven repo to resolvers

- tests/unit/src/test/scala/com/waz/service/AccountsSpec.scala
- zmessaging/src/main/scala/com/waz/api/impl/ZMessagingApi.scala
- zmessaging/src/main/scala/com/waz/service/AccountService.scala
- zmessaging/src/main/scala/com/waz/service/Accounts.scala
- zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
- New parameter for logout to clear credentials
- New methods to check team status in signup/signin
> Add account changes

- zmessaging/src/main/scala/com/waz/api/impl/search/UserSearchResult.scala
- zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
- zmessaging/src/main/scala/com/waz/service/UserService.scala
- zmessaging/src/main/scala/com/waz/service/teams/TeamsService.scala
- zmessaging/src/main/scala/com/waz/sync/client/UserSearchClient.scala
Also, a small change in UserSearchClient: In dev we sometimes retrieve user search entries without handles. They should be ignored.
> searches for guests ids, does not search for top people if on a team account

- tests/unit/src/test/scala/com/waz/service/AccountsServiceSpec.scala
- zmessaging/src/main/scala/com/waz/service/AccountManager.scala
- zmessaging/src/main/scala/com/waz/sync/otr/OtrClientsSyncHandler.scala
Merge sync self and sync user;
Only the accountId is passed along the chain;
Fix issue with verified account being set to false.
> Fix account manager flow

- zmessaging/src/main/scala/com/waz/service/PhoneNumberService.scala
The QA shortcut for phone numbers "+0" was not being recognized as a country number which made AccountsService, PhoneService and ContactsService behave a bit differently when tested with QA phone numbers than a real phone number.
> The QA shortcut passes as a country code

- tests/unit/src/test/scala/com/waz/service/teams/TeamsServiceSpec.scala
- zmessaging/src/main/scala/com/waz/service/teams/TeamsService.scala
Ticket: https://wearezeta.atlassian.net/browse/AN-5485
> [AN-5485] Fix to remove updated values from the search signal current value

- actors/base/src/main/scala/com/waz/provision/DeviceActor.scala
- tests/integration/src/test/scala/com/waz/conv/ConversationsListSpec.scala
- tests/integration/src/test/scala/com/waz/messages/AudioMessageSpec.scala
- tests/integration/src/test/scala/com/waz/messages/RichMediaSpec.scala
- tests/integration/src/test/scala/com/waz/messages/VideoMessageSpec.scala
- tests/mocked/src/test/scala/com/waz/mocked/notifications/NotificationsSyncSpec.scala
- tests/mocked/src/test/scala/com/waz/mocked/perf/InitialSyncPerformanceSpec.scala
- tests/unit/src/test/scala/com/waz/sync/SyncContentUpdaterSpec.scala
- tests/unit/src/test/scala/com/waz/sync/SyncExecutorSpec.scala
- tests/unit/src/test/scala/com/waz/sync/SyncRequestServiceImplSpec.scala
- tests/unit/src/test/scala/com/waz/sync/SyncRequestServiceSpec.scala
- tests/unit/src/test/scala/com/waz/sync/queue/SyncRequestSpec.scala
- tests/utils/src/main/scala/com/waz/specs/AndroidFreeSpec.scala
- zmessaging/src/main/scala/com/waz/content/MessagesStorage.scala
- zmessaging/src/main/scala/com/waz/content/SyncStorage.scala
- zmessaging/src/main/scala/com/waz/model/sync/SyncJob.scala
- zmessaging/src/main/scala/com/waz/model/sync/SyncRequest.scala
- zmessaging/src/main/scala/com/waz/service/AccountManager.scala
- zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
- zmessaging/src/main/scala/com/waz/sync/SyncRequestServiceImpl.scala
- zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
- zmessaging/src/main/scala/com/waz/sync/queue/SyncContentUpdater.scala
- zmessaging/src/main/scala/com/waz/sync/queue/SyncExecutor.scala
- zmessaging/src/main/scala/com/waz/sync/queue/SyncJobMerger.scala
- zmessaging/src/main/scala/com/waz/sync/queue/SyncScheduler.scala
- zmessaging/src/main/scala/com/waz/utils/wrappers/Intent.scala
- zmessaging/src/main/scala/com/waz/zms/SyncService.scala
Includes fix for removing stale jobs
> Sync scheduling refactoring

- zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
I switched from trying to update the cache with the exact match user to a new signal. It seems to be more direct and lightweight.
> [AN-5406] Exact match search by handle

- zmessaging/src/main/scala/com/waz/service/ContactsService.scala
- zmessaging/src/main/scala/com/waz/service/PhoneNumberService.scala
In most cases it's not used. Saves ~900kb of heap.
> using PhoneNumberUtil only when it's needed

- build.sbt
Fixes https://github.com/wireapp/wire-android/issues/1118
> Bump threetenbp version

- zmessaging/src/main/scala/com/waz/service/messages/MessageEventProcessor.scala
Added sanitization step during incoming message processing.
Currently limited to limiting text message lenght, may be extended in
future to perform more advance checks.
Fixes AN-5461
> Add incoming text message sanitization.

- tests/unit/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
- zmessaging/src/main/scala/com/waz/service/call/Avs.scala
- zmessaging/src/main/scala/com/waz/service/call/CallInfo.scala
- zmessaging/src/main/scala/com/waz/service/call/Calling.scala
- zmessaging/src/main/scala/com/waz/service/call/CallingService.scala
Wait with merge until testing is completed
> Re-enable CBR and update avs native api

- zmessaging/src/main/java/com/waz/api/IConversation.java
- zmessaging/src/main/scala/com/waz/api/ConversationsList.scala
- zmessaging/src/main/scala/com/waz/api/impl/Conversation.scala
- zmessaging/src/main/scala/com/waz/api/impl/ConversationsList.scala
- zmessaging/src/main/scala/com/waz/api/impl/conversation/BaseConversation.scala
- zmessaging/src/main/scala/com/waz/api/impl/conversation/SelfConversation.scala
- zmessaging/src/main/scala/com/waz/ui/Conversations.scala
Changes made during tracking the paths used in the application to change the current conversation. It's easier without this code getting in the way.
> Removes unused conversations code

- project/plugins.sbt
- zmessaging/src/main/jni/Android.mk
> [AN-5818] Fix build on Linux

- zmessaging/src/main/scala/com/waz/service/UserService.scala
- zmessaging/src/main/scala/com/waz/service/assets/AssetService.scala
This reverts commit 8a5a177f38fb922c8cf83f1571c5b7f6ca6e5319, reversing
changes made to 9e50169623159f4747965cefaf4655dc90b65a29.
> Revert "Merge pull request #284 from wireapp/profile-pictures-metadata"

- tests/unit/src/test/scala/com/waz/service/InvitationServiceSpec.scala
- tests/unit/src/test/scala/com/waz/service/UserSearchServiceSpec.scala
- zmessaging/src/main/scala/com/waz/content/MembersStorage.scala
- zmessaging/src/main/scala/com/waz/service/ContactsService.scala
- zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
- zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
- zmessaging/src/main/scala/com/waz/service/invitations/InvitationServiceImpl.scala
- zmessaging/src/main/scala/com/waz/sync/handler/InvitationSyncHandler.scala
Removes some unnecessary helper classes and brings all the search controller logic down to the search service. Still need to fix the tests
> Move search logic down to UserSearchService

- tests/unit/src/test/scala/com/waz/db/ZMessagingDBSpec.scala
- tests/unit/src/test/scala/com/waz/service/push/PushServiceSpec.scala
- zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
This is just temporarily ignoring the tests in PushServiceSpec until they can be fixed properly. Ditto the db tests, but those will require further work.
> [AN-5721] Fix tests and migration

- zmessaging/src/main/scala/com/waz/content/NotificationStorageImpl.scala
- zmessaging/src/main/scala/com/waz/content/Preferences.scala
- zmessaging/src/main/scala/com/waz/content/TeamsStorage.scala
- zmessaging/src/main/scala/com/waz/log/BufferedLogOutput.scala
- zmessaging/src/main/scala/com/waz/model/UserData.scala
- zmessaging/src/main/scala/com/waz/model/UserInfo.scala
- zmessaging/src/main/scala/com/waz/service/UserService.scala
- zmessaging/src/main/scala/com/waz/service/assets/AssetService.scala
- zmessaging/src/main/scala/com/waz/service/messages/MessagesService.scala
- zmessaging/src/main/scala/com/waz/sync/client/AssetClient.scala
- zmessaging/src/main/scala/com/waz/sync/handler/AssetSyncHandler.scala
- zmessaging/src/main/scala/com/waz/sync/handler/MessagesSyncHandler.scala
- zmessaging/src/main/scala/com/waz/sync/handler/OpenGraphSyncHandler.scala
- zmessaging/src/main/scala/com/waz/sync/handler/UsersSyncHandler.scala
- zmessaging/src/main/scala/com/waz/sync/otr/OtrSyncHandler.scala
This fixes our asset retention policies so they conform to the ones in the docs. This involved some renaming, which is done in the second commit for clarity, but should probably be merged into one once approved. Also some refactoring.
> Fix asset retention

- zmessaging/src/main/scala/com/waz/content/Preferences.scala
- zmessaging/src/main/scala/com/waz/service/AccountManager.scala
- zmessaging/src/main/scala/com/waz/service/AccountsService.scala
- zmessaging/src/main/scala/com/waz/sync/client/CredentialsUpdateClientImpl.scala
- zmessaging/src/main/scala/com/waz/znet/Response.scala
- Use this to display more accurate options
> Add hasPassword request

- zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
- zmessaging/src/main/scala/com/waz/service/messages/MessagesContentUpdater.scala
- zmessaging/src/main/scala/com/waz/service/messages/MessagesService.scala
https://github.com/wireapp/android-project/projects/6#card-8875322
> Use event timestamp for conversation creation message.

- zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
- zmessaging/src/main/scala/com/waz/model/PushNotificationEvents.scala
- zmessaging/src/main/scala/com/waz/service/push/PushNotificationEventsStorage.scala
- zmessaging/src/main/scala/com/waz/service/push/PushService.scala
- This more accurately reflects what we use as a primary key now
> Change primary key to index column

- zmessaging/src/main/scala/com/waz/model/Mime.scala
https://github.com/wireapp/android-project/issues/86
> Remove tiff from the list of supported images and enforce it

- zmessaging/src/main/scala/com/waz/service/messages/ReceiptService.scala
https://github.com/wireapp/android-project/issues/78
https://github.com/wireapp/android-project/issues/79
> Delivery receipts for teams

- zmessaging/src/main/scala/com/waz/content/Preferences.scala
This is for issue https://github.com/wireapp/android-project/issues/116
> Add preference for storing notifications

- zmessaging/src/main/scala/com/waz/content/AssetsStorage.scala
- zmessaging/src/main/scala/com/waz/service/assets/AssetService.scala
- zmessaging/src/main/scala/com/waz/utils/Cancellable.scala
fixes https://github.com/wireapp/android-project/issues/130
> When cancelling upload, delete only files from content

- zmessaging/src/main/scala/com/waz/sync/client/OpenGraphClient.scala
I think that we can extract open graph data without checking the page type. If we can extract image and tittle, it should be enough to render web page preview.
> Remove OpenGraph data parsing restrictions.

- zmessaging/src/main/scala/com/waz/sync/client/CallingClient.scala
> Update call config endpoint

- zmessaging/src/main/scala/com/waz/sync/handler/AssetSyncHandler.scala
- zmessaging/src/main/scala/com/waz/sync/handler/MessagesSyncHandler.scala
- zmessaging/src/main/scala/com/waz/sync/handler/OpenGraphSyncHandler.scala
- zmessaging/src/main/scala/com/waz/sync/handler/UsersSyncHandler.scala
fixes https://github.com/wireapp/android-project/issues/176
> Fix asset messages having their timestamp resent on resending

- zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
> Optimize signal to avoid active aggregate signal from being recreated

- zmessaging/src/main/scala/com/waz/service/media/RichMediaContentParser.scala
- zmessaging/src/main/scala/com/waz/sync/client/OpenGraphClient.scala
- zmessaging/src/main/scala/com/waz/znet2/HttpClientOkHttpImpl.scala
Also allow CLEARTEX connections for opengraph client.
fixes https://github.com/wireapp/android-project/issues/184
> Handle unresolved websites as no opengraph data

- zmessaging/src/main/scala/com/waz/api/AssetFactory.scala
- zmessaging/src/main/scala/com/waz/model/AssetData.scala
- zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
- zmessaging/src/main/scala/com/waz/sync/handler/AssetSyncHandler.scala
Just after merging this PR, https://github.com/wireapp/wire-android/pull/1693 in UI has to be merged as well.
> Bump file size limit to 100MB for teams (bringing back reverted code)

- tests/unit/src/test/scala/com/waz/service/call/CallInfoSpec.scala
- zmessaging/src/main/scala/com/waz/service/call/CallInfo.scala
fixes https://github.com/wireapp/android-project/issues/225
> Prevent established time from being reset

- tests/unit/src/test/scala/com/waz/service/UserSearchServiceSpec.scala
- zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
This allows to perform search using a text query for participants in a conversation which will be needed for mentions.
> Add users search for a specific conversation

- tests/unit/src/test/scala/com/waz/service/UserSearchServiceSpec.scala
- zmessaging/src/main/scala/com/waz/service/SearchKey.scala
- zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
- Adds new sorting rules for search results
- Now supports tokenizing search
> feat: Add new search algorithm for mentions

- zmessaging/src/main/scala/com/waz/service/ConnectionService.scala
Fixes https://github.com/wireapp/android-project/issues/255
Notes for tester:
Scenario for test is described by @red-avtovo inside the issue.
> Fix white screen bug

- zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
The work manager and our implementation doesn't seem production ready yet, we should work to improve it before releasing it.
> fix: Revert changes to use work manager

- zmessaging/src/main/scala/com/waz/log/ZLog2.scala
- zmessaging/src/main/scala/com/waz/model/AccountDataOld.scala
- zmessaging/src/main/scala/com/waz/model/SSOId.scala
- zmessaging/src/main/scala/com/waz/service/ReportingService.scala
fixes: https://github.com/wireapp/android-project/issues/372
> fix: Remove sensitive information from internal logging system

- zmessaging/src/main/scala/com/waz/service/GlobalModule.scala
- zmessaging/src/main/scala/com/waz/service/MetaDataService.scala
- zmessaging/src/main/scala/com/waz/znet2/HttpClientOkHttpImpl.scala
- zmessaging/src/main/scala/com/waz/znet2/OkHttpUserAgentInterceptor.scala
- zmessaging/src/test/scala/com/waz/AuthenticationConfig.scala
Now we will specify our custom "User-Agent" header for each http request:
s"Android $androidVersion / Wire $wireVersion / HttpLibrary $okHttpDefaultUserAgent"
> feature: custom user agent header

- zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
- zmessaging/src/main/scala/com/waz/log/ZLog2.scala
- zmessaging/src/main/scala/com/waz/model/ManagedBy.scala
- zmessaging/src/main/scala/com/waz/model/SSOId.scala
- zmessaging/src/main/scala/com/waz/model/UserData.scala
- zmessaging/src/main/scala/com/waz/model/UserInfo.scala
- This flag indicates whether the user should be allowed to edit their
profile or not, and so we have to store it locally.
> feat: add parsing of managedBy flag from BE

- zmessaging/src/main/java/com/waz/model/sync/SyncCommand.java
- zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
- zmessaging/src/main/scala/com/waz/model/UserData.scala
- zmessaging/src/main/scala/com/waz/model/UserField.scala
- zmessaging/src/main/scala/com/waz/model/UserInfo.scala
- zmessaging/src/main/scala/com/waz/model/sync/SyncRequest.scala
- zmessaging/src/main/scala/com/waz/service/UserService.scala
- zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
- zmessaging/src/main/scala/com/waz/sync/client/UsersClient.scala
- zmessaging/src/main/scala/com/waz/sync/handler/UsersSyncHandler.scala
- zmessaging/src/test/scala/com/waz/model/UserDataSpec.scala
- zmessaging/src/test/scala/com/waz/model/UserFieldSpec.scala
This can't be easily tested, due to this not being finished on the backend side, but for now there is a sync job(`SyncRichInfo` which takes a list of user ids) for fetching RichInfo. I'll be working on adding tests to try and make sure the JSON parsing works at least.
> feat: Add column to UserData for profile fields

- zmessaging/src/main/scala/com/waz/sync/handler/MessagesSyncHandler.scala
Previously, the ID of the message would change during an edit. The code was looking for a message with a given ID to mark it as `SENT`, but the ID was already changed and no message was found, leaving the message in the `PENDING` state.
This only affected the sender, the receiver would receive the edit.
- Propagate the ID of the message that has been sent. In case of edits, the message ID is changed and we are now propagating the new ID.
I could not easily test this at the unit test level. The amount of mock necessary to test this is quite demanding. I manually tested on device before and after the fix. Steps:
- Open a conversation
- Enter a text message
- Send and wait until it's marked as "sent"
- Edit the message
- Send
Result before the fix:
- The edited message is shown as "pending" …
> Fix: edited messages are now marked as sent

- zmessaging/src/main/scala/com/waz/service/teams/TeamsService.scala
- zmessaging/src/test/scala/com/waz/service/teams/TeamsServiceSpec.scala
Fixing a bug where we don't store `created_by` field for the self user during a member update
Added unit test for:
- storing `created_by` during member update
- storing self permissions during member update (unrelated to this bug, but was missing)
This PR is a clean up version of https://github.com/wireapp/wire-android-sync-engine/pull/509
> fix: store `created_by` for self user

- zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
Fixing a bug with search
A member of the team could not find people from the search directory anymore
The directory was erroneously filtered by users that are in visible in the team
Remove filtering
I could not come up with a decent unit test for this as the amount of mocking required is staggering. I manually tested on device before and after the fix.
Steps:
- log in as an admin
- open search
- search for a name that you know to be a consumer account that you are not connected to
- BEFORE THE FIX: no user found
- AFTER THE FIX: user is found
This PR is a clean up version of #509
> fix: restore ability to search for non-team members

- zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
- zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
- zmessaging/src/main/scala/com/waz/service/push/FCMNotificationsRepository.scala
This PR adds the first table/repository required for notification tracking.
> feat: add table to track notification latency

- zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
- zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
- zmessaging/src/main/scala/com/waz/service/push/FCMNotificationStatsRepository.scala
Add the table of statistics which will be populated by notification tracking. This PR should be merged only after [ReceivedPushes PR](https://github.com/wireapp/wire-android-sync-engine/pull/515) has been merged.
> Add stats table

- zmessaging/src/main/scala/com/waz/model/FCMNotification.scala
- zmessaging/src/main/scala/com/waz/repository/FCMNotificationStatsRepository.scala
- zmessaging/src/main/scala/com/waz/service/FCMNotificationStatsService.scala
- zmessaging/src/main/scala/com/waz/service/push/PushService.scala
- zmessaging/src/test/scala/com/waz/model/FCMNotificationStatsServiceSpec.scala
Write timestamps and stats for each stage
> Write stages

- zmessaging/src/main/scala/com/waz/service/FCMNotificationStatsService.scala
- zmessaging/src/main/scala/com/waz/service/ReportingService.scala
Add writing of formatted stats to debug log
> Listing stats

- zmessaging/src/main/java/com/waz/model/sync/SyncCommand.java
- zmessaging/src/main/scala/com/waz/content/Preferences.scala
All that is needed for the "Email in the rich profile" feature in SE is that we should re-import user data from the backend. If this is done, we should get updated emails which then will be displayed in the rich profile.
> Sync users from the backend

- zmessaging/src/main/scala/com/waz/service/push/PushService.scala
- zmessaging/src/main/scala/com/waz/sync/queue/SyncExecutor.scala
I added log lines to the events' processing in `PushService` and changed a bit the implementation of the event handler there. I would like to merge these changes to Internal, so that we can test it on a range of devices and gather more information. The recent changes in UI should "unstuck" the app, so that if the bug occurs, the user should be able to still use it, but the moving line at the top will indicate that we're still syncing.
I would also like to check if my change to the event handler helps with that. I don't know this part of the code very well, but I suspect that throwing an exception in case of a failed event might have caused the event processing to restart without removing the failed event before - hence, an infinite loop.
> The event handler in PushService should not throw exception + log lines

- zmessaging/src/main/scala/com/waz/content/Preferences.scala
Reset log flag to off, this is related to #537
> fix: Reset debug flag to off for all users

- build.sbt
Major API changes have been introduce by the assets refactoring.
> chore: bump major version to mark assets refactoring

- zmessaging/src/main/scala/com/waz/model/MessageData.scala
The previous fix of markdown links worked only on the receiver's side.
> fix: Markdown links should not generate previews also on the sender's side.

- zmessaging/src/main/scala/com/waz/service/messages/MessagesService.scala
This method is deprecated and no longer used in SE or UI. I noticed this whilst working on the YouTube preview bug.
> refactor: remove unused retention method

- zmessaging/src/main/scala/com/waz/service/GlobalModule.scala
- zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
- zmessaging/src/main/scala/com/waz/znet2/HttpClientOkHttpImpl.scala
- zmessaging/src/main/scala/com/waz/znet2/WebSocketFactory.scala
- zmessaging/src/test/scala/com/waz/znet2/OkHttpWebSocketSpec.scala
- This commit adds the ability to specify an HTTP proxy at compile time
- AN-6291
- It was tested manually using tinyproxy locally
> feat: add http proxy support

- zmessaging/src/main/scala/com/waz/service/assets2/AssetService.scala
`AssetService.loadContentById` loaded an asset from the storage using its id, and then called `loadContent`, which again used `asset.id` to find that asset. Now both methods use another private method for loading the asset, so there's no need to access the storage twice.
> refactor: A small optimization in loading assets

- zmessaging/src/main/scala/com/waz/model/Uid.scala
- zmessaging/src/main/scala/com/waz/model/messages/media/MediaAssetData.scala
- zmessaging/src/main/scala/com/waz/model/messages/media/MediaAssetDataProtocol.scala
- zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
- zmessaging/src/main/scala/com/waz/service/media/YouTubeMediaService.scala
- zmessaging/src/main/scala/com/waz/service/messages/MessagesService.scala
- zmessaging/src/main/scala/com/waz/sync/client/YouTubeClient.scala
- zmessaging/src/main/scala/com/waz/utils/JsonDecoder.scala
- zmessaging/src/test/scala/com/waz/service/MessagesServiceSpec.scala
- zmessaging/src/test/scala/com/waz/service/media/YouTubeMediaServiceSpec.scala
- This commit adds the ability to specify an HTTP proxy at compile time
- [AN-6028](https://wearezeta.atlassian.net/browse/AN-6028)
- It was tested manually using tinyproxy locally
> fix: youtube preview images
